program Plan9Basic;

uses
  System.StartUpCopy,
  FMX.Forms,
  UnitMain in 'UnitMain.pas' {frmMain},
  basic in 'basic.pas',
  exec in 'exec.pas',
  lexer in 'lexer.pas',
  parser in 'parser.pas',
  UnitUtils in 'UnitUtils.pas',
  TranslationManager in 'utils\TranslationManager.pas',
  UnitGC in 'utils\UnitGC.pas',
  HandleRegistry in 'utils\HandleRegistry.pas',
  BasicConsole in 'utils\BasicConsole.pas',
  ArrayLib in 'Libs\ArrayLib.pas',
  DateTimeLib in 'Libs\DateTimeLib.pas',
  NumLib in 'Libs\NumLib.pas',
  StdLib in 'Libs\StdLib.pas',
  StrLib in 'Libs\StrLib.pas',
  SysLib in 'Libs\SysLib.pas',
  PlatformInfoLib in 'Libs\PlatformInfoLib.pas',
  DictLib in 'Libs\DictLib.pas',
  ConfigLib in 'Libs\ConfigLib.pas',
  StrListLib in 'Libs\StrListLib.pas',
  JsonLib in 'Libs\JsonLib.pas',
  RegexLib in 'Libs\RegexLib.pas',
  Base64Lib in 'Libs\Base64Lib.pas',
  GzipLib in 'Libs\GzipLib.pas',
  ZipLib in 'Libs\ZipLib.pas',
  HttpLib in 'Libs\HttpLib.pas',
  FormLib in 'Libs\GUI\FormLib.pas',
  LayoutLib in 'Libs\GUI\LayoutLib.pas',
  RectangleLib in 'Libs\GUI\RectangleLib.pas',
  LabelLib in 'Libs\GUI\LabelLib.pas',
  EditLib in 'Libs\GUI\EditLib.pas',
  MemoLib in 'Libs\GUI\MemoLib.pas',
  ButtonLib in 'Libs\GUI\ButtonLib.pas',
  SpeedButtonLib in 'Libs\GUI\SpeedButtonLib.pas',
  ComboBoxLib in 'Libs\GUI\ComboBoxLib.pas',
  ListBoxLib in 'Libs\GUI\ListBoxLib.pas',
  CheckBoxLib in 'Libs\GUI\CheckBoxLib.pas',
  RadioButtonLib in 'Libs\GUI\RadioButtonLib.pas',
  PanelLib in 'Libs\GUI\PanelLib.pas',
  CircleLib in 'Libs\GUI\CircleLib.pas',
  RoundRectLib in 'Libs\GUI\RoundRectLib.pas',
  EllipseLib in 'Libs\GUI\EllipseLib.pas',
  ArcLib in 'Libs\GUI\ArcLib.pas',
  PieLib in 'Libs\GUI\PieLib.pas',
  LineLib in 'Libs\GUI\LineLib.pas',
  CalloutRectangleLib in 'Libs\GUI\CalloutRectangleLib.pas',
  PathLib in 'Libs\GUI\PathLib.pas',
  ImageLib in 'Libs\GUI\ImageLib.pas',
  SwitchLib in 'Libs\GUI\SwitchLib.pas',
  StringGridLib in 'Libs\GUI\StringGridLib.pas',
  ProgressBarLib in 'Libs\GUI\ProgressBarLib.pas',
  TrackBarLib in 'Libs\GUI\TrackBarLib.pas',
  TimerLib in 'Libs\GUI\TimerLib.pas',
  ScrollBoxLib in 'Libs\GUI\ScrollBoxLib.pas',
  ColorAnimationLib in 'Libs\GUI\Animations\ColorAnimationLib.pas',
  FloatAnimationLib in 'Libs\GUI\Animations\FloatAnimationLib.pas',
  IntAnimationLib in 'Libs\GUI\Animations\IntAnimationLib.pas',
  BitmapListAnimationLib in 'Libs\GUI\Animations\BitmapListAnimationLib.pas',
  PathAnimationLib in 'Libs\GUI\Animations\PathAnimationLib.pas',
  RectAnimationLib in 'Libs\GUI\Animations\RectAnimationLib.pas',
  BlurEffectLib in 'Libs\GUI\Effects\BlurEffectLib.pas',
  GlowEffectLib in 'Libs\GUI\Effects\GlowEffectLib.pas',
  ShadowEffectLib in 'Libs\GUI\Effects\ShadowEffectLib.pas',
  BevelEffectLib in 'Libs\GUI\Effects\BevelEffectLib.pas',
  ColorKeyAlphaEffectLib in 'Libs\GUI\Effects\ColorKeyAlphaEffectLib.pas',
  InnerGlowEffectLib in 'Libs\GUI\Effects\InnerGlowEffectLib.pas',
  MonochromeEffectLib in 'Libs\GUI\Effects\MonochromeEffectLib.pas',
  ReflectionEffectLib in 'Libs\GUI\Effects\ReflectionEffectLib.pas',
  ContrastEffectLib in 'Libs\GUI\Effects\ContrastEffectLib.pas',
  HueAdjustEffectLib in 'Libs\GUI\Effects\HueAdjustEffectLib.pas',
  InvertEffectLib in 'Libs\GUI\Effects\InvertEffectLib.pas',
  SepiaEffectLib in 'Libs\GUI\Effects\SepiaEffectLib.pas',
  EmbossEffectLib in 'Libs\GUI\Effects\EmbossEffectLib.pas',
  PaperSketchEffectLib in 'Libs\GUI\Effects\PaperSketchEffectLib.pas',
  PencilStrokeEffectLib in 'Libs\GUI\Effects\PencilStrokeEffectLib.pas',
  PixelateEffectLib in 'Libs\GUI\Effects\PixelateEffectLib.pas',
  SharpenEffectLib in 'Libs\GUI\Effects\SharpenEffectLib.pas',
  ToonEffectLib in 'Libs\GUI\Effects\ToonEffectLib.pas',
  BandsEffectLib in 'Libs\GUI\Effects\BandsEffectLib.pas',
  MagnifyEffectLib in 'Libs\GUI\Effects\MagnifyEffectLib.pas',
  RippleEffectLib in 'Libs\GUI\Effects\RippleEffectLib.pas',
  SwirlEffectLib in 'Libs\GUI\Effects\SwirlEffectLib.pas',
  WaveEffectLib in 'Libs\GUI\Effects\WaveEffectLib.pas',
  WrapEffectLib in 'Libs\GUI\Effects\WrapEffectLib.pas',
  BlindTransitionEffectLib in 'Libs\GUI\Effects\BlindTransitionEffectLib.pas',
  CircleTransitionEffectLib in 'Libs\GUI\Effects\CircleTransitionEffectLib.pas',
  DissolveTransitionEffectLib in 'Libs\GUI\Effects\DissolveTransitionEffectLib.pas',
  FadeTransitionEffectLib in 'Libs\GUI\Effects\FadeTransitionEffectLib.pas',
  SlideTransitionEffectLib in 'Libs\GUI\Effects\SlideTransitionEffectLib.pas',
  SWipeTransitionEffectLib in 'Libs\GUI\Effects\SWipeTransitionEffectLib.pas',
  BloodTransitionEffectLib in 'Libs\GUI\Effects\BloodTransitionEffectLib.pas',
  BlurTransitionEffectLib in 'Libs\GUI\Effects\BlurTransitionEffectLib.pas',
  BrightTransitionEffectLib in 'Libs\GUI\Effects\BrightTransitionEffectLib.pas',
  CrumpleTransitionEffectLib in 'Libs\GUI\Effects\CrumpleTransitionEffectLib.pas',
  DropTransitionEffectLib in 'Libs\GUI\Effects\DropTransitionEffectLib.pas',
  LineTransitionEffectLib in 'Libs\GUI\Effects\LineTransitionEffectLib.pas',
  MagnifyTransitionEffectLib in 'Libs\GUI\Effects\MagnifyTransitionEffectLib.pas',
  PixelateTransitionEffectLib in 'Libs\GUI\Effects\PixelateTransitionEffectLib.pas',
  RotateCrumpleTransitionEffectLib in 'Libs\GUI\Effects\RotateCrumpleTransitionEffectLib.pas',
  SaturateTransitionEffectLib in 'Libs\GUI\Effects\SaturateTransitionEffectLib.pas',
  ShapeTransitionEffectLib in 'Libs\GUI\Effects\ShapeTransitionEffectLib.pas',
  SwirlTransitionEffectLib in 'Libs\GUI\Effects\SwirlTransitionEffectLib.pas',
  WaterTransitionEffectLib in 'Libs\GUI\Effects\WaterTransitionEffectLib.pas',
  WaveTransitionEffectLib in 'Libs\GUI\Effects\WaveTransitionEffectLib.pas',
  WiggleTransitionEffectLib in 'Libs\GUI\Effects\WiggleTransitionEffectLib.pas',
  RippleTransitionEffectLib in 'Libs\GUI\Effects\RippleTransitionEffectLib.pas',
  BoxBlurEffectLib in 'Libs\GUI\Effects\BoxBlurEffectLib.pas',
  DirectionalBlurEffectLib in 'Libs\GUI\Effects\DirectionalBlurEffectLib.pas',
  GaussianBlurEffectLib in 'Libs\GUI\Effects\GaussianBlurEffectLib.pas',
  RadialBlurEffectLib in 'Libs\GUI\Effects\RadialBlurEffectLib.pas',
  BloomEffectLib in 'Libs\GUI\Effects\BloomEffectLib.pas',
  GloomEffectLib in 'Libs\GUI\Effects\GloomEffectLib.pas',
  AffineTransformEffectLib in 'Libs\GUI\Effects\AffineTransformEffectLib.pas',
  CropEffectLib in 'Libs\GUI\Effects\CropEffectLib.pas',
  PerspectiveTransformEffectLib in 'Libs\GUI\Effects\PerspectiveTransformEffectLib.pas',
  TilerEffectLib in 'Libs\GUI\Effects\TilerEffectLib.pas',
  BandedSwirlTransitionEffectLib in 'Libs\GUI\Effects\BandedSwirlTransitionEffectLib.pas',
  FillEffectLib in 'Libs\GUI\Effects\FillEffectLib.pas',
  FillRGBEffectLib in 'Libs\GUI\Effects\FillRGBEffectLib.pas',
  MaskToAlphaEffectLib in 'Libs\GUI\Effects\MaskToAlphaEffectLib.pas',
  NormalBlendEffectLib in 'Libs\GUI\Effects\NormalBlendEffectLib.pas',
  PinchEffectLib in 'Libs\GUI\Effects\PinchEffectLib.pas',
  SmoothMagnifyEffectLib in 'Libs\GUI\Effects\SmoothMagnifyEffectLib.pas',
  BandedSwirlEffectLib in 'Libs\GUI\Effects\BandedSwirlEffectLib.pas',
  MediaPlayerLib in 'Libs\GUI\MediaPlayerLib.pas',
  SQLiteLib in 'Libs\SQLiteLib.pas',
  IOUtilsLib in 'Libs\IOUtilsLib.pas',
  AILib in 'Libs\AI\AILib.pas',
  RAGEngine in 'Libs\AI\RAGEngine.pas',
  RAGLib in 'Libs\AI\RAGLib.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
