#!/usr/bin/env python3
r"""Generate the composite-geometry round for every control library.

move, size, bounds, margin and margins take their values as a group and are
read back one at a time. That makes them the one family where a test can assert
what the call *did* rather than only that it could be made -- and the failure
they invite is the one Phase 1 already found once in StrLib: arguments in the
wrong order, which compiles, runs, reports nothing, and puts the height in the
width.

So the values are all different from each other. move(11, 22) with x and y
swapped reads back 22 and 11, and the assertion names which one moved.

    move#(c, 11, 22)         -> x = 11, y = 22
    size#(c, 33, 44)         -> width = 33, height = 44
    bounds#(c, 5, 6, 7, 8)   -> x, y, width, height in that order
    margin#(c, 3)            -> all four sides
    margins#(c, 1, 2, 3, 4)  -> left, top, right, bottom

bringtofront, sendtoback, parent and clearcallbacks change nothing a getter can
see, so they are asserted to be callable without recording an error, which is
the most that can honestly be claimed from BASIC.

    python tests/gen_geometry_suite.py
    python tests/gen_geometry_suite.py --check

Writes tests/gui/10_geometry.bas.
"""
import os
import re
import sys
import glob
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GUI = os.path.join(ROOT, 'Libs', 'GUI')
OUT = os.path.join(ROOT, 'tests', 'gui', '10_geometry.bas')
SIG = re.compile(r"Lib\.Add\('([a-z0-9_]+)([#$]?)@([#n$]*)'")

SIDES = ('left', 'top', 'right', 'bottom')


def read():
    """Every registered name, as lib -> {tail|ret@params}."""
    have, ctor = defaultdict(set), {}
    for p in glob.glob(os.path.join(GUI, '*.pas')):
        text = open(p, encoding='utf-8-sig', errors='replace').read()
        for name, ret, params in SIG.findall(text):
            if '_' not in name:
                if ret == '#' and params == '#':
                    ctor[name] = True
                continue
            lib, tail = name.split('_', 1)
            have[lib].add(tail + '|' + ret + '@' + params)
    return have, ctor


def main():
    have, ctor = read()

    def has(lib, tail, form):
        return (tail + '|' + form) in have[lib]

    libs = sorted(l for l in ctor if has(l, 'x', '@#') and has(l, 'y', '@#'))

    out = [
        'rem ---------------------------------------------------------------',
        'rem Composite geometry: what the call did, not that it could be made.',
        'rem',
        'rem Generated by tests/gen_geometry_suite.py -- edit that, not this.',
        'rem',
        'rem move, size, bounds, margin and margins take their values as a group',
        'rem and are read back one at a time, which is the only family where a',
        'rem test can assert the effect. The failure they invite is the one',
        'rem Phase 1 found in StrLib: arguments in the wrong order, which',
        'rem compiles, runs, reports nothing, and puts the height in the width.',
        'rem',
        'rem Every value is different from every other, so a swap reads back as',
        'rem the wrong number rather than the right one.',
        'rem ---------------------------------------------------------------',
        '',
        'f# = form#()',
        '',
        'rem An aligned control does not own its position: the parent lays it',
        'rem out, and move, bounds and size are overwritten with no error',
        'rem reported. That is FMX and it is true of every control, but it is',
        'rem invisible from BASIC, so it is stated here rather than left for',
        'rem somebody to rediscover. scrollbox#(parent#) aligns Client, which',
        'rem is how this suite found it.',
        'test_case("geometry/an aligned control ignores move")',
        'a# = rectangle#(f#)',
        'rectangle_align#(a#, 9)',
        'rectangle_move#(a#, 11, 22)',
        'assert_eq(rectangle_x(a#), 0, "Client alignment kept x at 0")',
        'assert_eq(rectangle_error(), 0, "and move reported no error doing it")',
        'rectangle_align#(a#, 0)',
        'rectangle_move#(a#, 11, 22)',
        'assert_eq(rectangle_x(a#), 11, "with alignment off the same call works")',
        '',
    ]
    n = 0
    for lib in libs:
        body = []
        if has(lib, 'move', '#@#nn'):
            body += ['%s_move#(c#, 11, 22)' % lib,
                     'assert_eq(%s_x(c#), 11, "%s_move set x")' % (lib, lib),
                     'assert_eq(%s_y(c#), 22, "%s_move set y, not x")' % (lib, lib)]
        if has(lib, 'size', '#@#nn') and has(lib, 'width', '@#') and has(lib, 'height', '@#'):
            body += ['%s_size#(c#, 33, 44)' % lib,
                     'assert_eq(%s_width(c#), 33, "%s_size set width")' % (lib, lib),
                     'assert_eq(%s_height(c#), 44, "%s_size set height, not width")' % (lib, lib)]
        if has(lib, 'bounds', '#@#nnnn') and has(lib, 'width', '@#') and has(lib, 'height', '@#'):
            body += ['%s_bounds#(c#, 5, 6, 7, 8)' % lib,
                     'assert_eq(%s_x(c#), 5, "%s_bounds x")' % (lib, lib),
                     'assert_eq(%s_y(c#), 6, "%s_bounds y")' % (lib, lib),
                     'assert_eq(%s_width(c#), 7, "%s_bounds width")' % (lib, lib),
                     'assert_eq(%s_height(c#), 8, "%s_bounds height")' % (lib, lib)]
        if has(lib, 'margin', '#@#n') and all(has(lib, 'margin' + s, '@#') for s in SIDES):
            body += ['%s_margin#(c#, 3)' % lib]
            body += ['assert_eq(%s_margin%s(c#), 3, "%s_margin set %s")'
                     % (lib, s, lib, s) for s in SIDES]
        if has(lib, 'margins', '#@#nnnn') and all(has(lib, 'margin' + s, '@#') for s in SIDES):
            body += ['%s_margins#(c#, 1, 2, 3, 4)' % lib]
            body += ['assert_eq(%s_margin%s(c#), %d, "%s_margins %s")'
                     % (lib, s, i + 1, lib, s) for i, s in enumerate(SIDES)]
        #No getter can see these, so the claim is only that they are callable.
        for tail, form in (('bringtofront', '#@#'), ('sendtoback', '#@#'),
                           ('clearcallbacks', '#@#')):
            if has(lib, tail, form):
                body += ['%s_%s#(c#)' % (lib, tail),
                         'assert_eq(%s_error(), 0, "%s_%s is callable")'
                         % (lib, lib, tail)]
        if not body:
            continue
        head = ['test_case("geometry/%s")' % lib,
                'c# = %s#(f#)' % lib,
                '%s_clearerror()' % lib]
        #An aligned control's position and size belong to the parent's layout,
        #so move and bounds are silently ignored on one -- see the preamble.
        #scrollbox#(parent#) aligns Client, which is how this was found.
        if has(lib, 'align', '#@#n'):
            head.append('%s_align#(c#, 0)' % lib)
        out += head + body + ['']

    text = '\n'.join(out)
    #counted from what was emitted rather than multiplied by a
    #number somebody remembered; the lifecycle generator got that
    #wrong yesterday and its own run contradicted it.
    n = sum(1 for line in out if line.startswith('assert_'))
    rel = os.path.relpath(OUT, ROOT).replace(os.sep, '/')
    if '--check' in sys.argv:
        if not os.path.isfile(OUT):
            print('  %s is missing; run this without --check' % rel)
            return 1
        have_text = open(OUT, encoding='utf-8', newline='').read()
        if have_text.replace(chr(13) + chr(10), chr(10)) != text:
            print('  %s is not what its generator produces now' % rel)
            print('  run: python tests/gen_geometry_suite.py')
            return 1
        print('ok  %s matches its generator, %d assertion(s)' % (rel, n))
        return 0

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('%s: %d assertions' % (rel, n))
    return 0


if __name__ == '__main__':
    sys.exit(main())
