#!/usr/bin/env python3
r"""Generate a round trip over every property a control library exposes.

The GUI suite exercised 20% of the registered GUI surface. Everything this
project has found by running rather than reading came out of that other 80%:
SQLiteLib and RAGLib were dead, 25 *_free functions always answered 0, an
assertion about scrollbox parents had never been true, and ScrollBoxLib itself
was failing every call since the HandleRegistry conversion -- found the day
tests/gui/04_alignment.bas was generated over 26 controls, not before.

So this does the same for the properties. For every library with a constructor,
an error accessor, and a property carrying both a setter and a getter of the
same type, it emits:

    v = lib_prop(c#)              read it
    assert lib_error() = 0
    lib_prop#(c#, v)              write back exactly what was read
    assert lib_error() = 0

Writing back the value already there is deliberate. A setter may clamp, or
round, or refuse a value outside its range, and asserting that an invented value
survives would report those as failures -- noise that buries the signal. What
this asserts is narrower and is the thing that has actually been wrong: that the
call can be made at all, and that neither half reports an error.

    python tests/gen_property_suite.py

Writes tests/gui/08_property_roundtrip.bas.
"""
import os
import re
import sys
import glob
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GUI = os.path.join(ROOT, 'Libs', 'GUI')
OUT = os.path.join(ROOT, 'tests', 'gui', '08_property_roundtrip.bas')

SIG = re.compile(r"Lib\.Add\('([a-z0-9_]+)([#$]?)@([#n$]*)'")

#Controls only: the effect and animation libraries attach to a control rather
#than being one, and tests/gui/03_effects.bas already covers them.
def control_units():
    for p in sorted(glob.glob(os.path.join(GUI, '*.pas'))):
        if os.path.basename(p) not in ('ControlCommon.pas', 'GuiUtils.pas'):
            yield p


def read():
    setters, getters, ctors, errors = (defaultdict(dict), defaultdict(dict),
                                       defaultdict(set), set())
    for p in control_units():
        text = open(p, encoding='utf-8-sig', errors='replace').read()
        for name, ret, params in SIG.findall(text):
            if name.endswith('_error') and params == '':
                errors.add(name[:-6])
            if '_' not in name:
                if ret == '#':
                    ctors[name].add(params)
                continue
            lib, prop = name.split('_', 1)
            if ret == '#' and len(params) == 2 and params[0] == '#':
                setters[lib][prop] = params[1]
            elif params == '#' and ret in ('$', ''):
                getters[lib][prop] = ret or 'n'
    return setters, getters, ctors, errors


def main():
    setters, getters, ctors, errors = read()
    libs = sorted(l for l in ctors
                  if l in errors and '#' in ctors[l]
                  and (set(setters[l]) & set(getters[l])))

    out = [
        'rem ---------------------------------------------------------------',
        'rem Every property a control exposes, read and written back.',
        'rem',
        'rem Generated by tests/gen_property_suite.py -- edit that, not this.',
        'rem',
        'rem The value written is the value just read, so a setter that clamps',
        'rem or rounds is not reported as a failure. What is asserted is that',
        'rem the call can be made and that neither half records an error, which',
        'rem is what was wrong when ScrollBoxLib answered error 1 to everything',
        'rem it was asked for and nothing noticed.',
        'rem ---------------------------------------------------------------',
        '',
        'f# = form#()',
        '',
    ]
    pairs = 0
    for lib in libs:
        common = sorted(p for p in (set(setters[lib]) & set(getters[lib]))
                        if (setters[lib][p] == '$') == (getters[lib][p] == '$'))
        if not common:
            continue
        out.append('test_case("property/%s")' % lib)
        out.append('c# = %s#(f#)' % lib)
        out.append('assert_eq(%s_error(), 0, "%s#() built a control")' % (lib, lib))
        for prop in common:
            kind = getters[lib][prop]
            if kind == '$':
                out.append('s$ = %s_%s$(c#)' % (lib, prop))
                out.append('assert_eq(%s_error(), 0, "%s_%s$ reads")'
                           % (lib, lib, prop))
                out.append('%s_%s#(c#, s$)' % (lib, prop))
            else:
                out.append('v = %s_%s(c#)' % (lib, prop))
                out.append('assert_eq(%s_error(), 0, "%s_%s reads")'
                           % (lib, lib, prop))
                out.append('%s_%s#(c#, v)' % (lib, prop))
            out.append('assert_eq(%s_error(), 0, "%s_%s writes back what it read")'
                       % (lib, lib, prop))
            pairs += 1
        out.append('')

    text = '\n'.join(out)
    rel = os.path.relpath(OUT, ROOT).replace(os.sep, '/')

    #--check writes nothing and answers whether the committed file is what
    #this would produce now. A generator and its output are two artefacts,
    #and two artefacts drift: adding a control library without regenerating
    #leaves the suite silently describing the tree as it used to be.
    if '--check' in sys.argv:
        if not os.path.isfile(OUT):
            print('  %s does not exist; run this without --check' % rel)
            return 1
        have = open(OUT, encoding='utf-8', newline='').read()
        if have.replace('\r\n', '\n') != text:
            print('  %s is not what its generator produces now' % rel)
            print('  run: python tests/gen_property_suite.py')
            return 1
        print('ok  %s matches its generator, %d property round trip(s)'
              % (rel, pairs))
        return 0

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('%s: %d library(ies), %d property(ies), %d assertion(s)'
          % (rel, len(libs), pairs, pairs * 2 + len(libs)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
