#!/usr/bin/env python3
r"""Generate the lifecycle and error-reporting round for every GUI library.

Four families went untested: free (99 functions), error (98), errormsg (97),
strerror (98) and clearerror (98). Between them that is a quarter of the GUI
surface, and it is the quarter where the failures are silent by construction --
a free that reports success without freeing, or an error slot that never
clears, looks exactly like a working library from a BASIC program.

The history is on the record. Twenty-five *_free functions answered 0 on every
call, for months, because the block that set the result had been commented out;
n_rect_free still carries the note. Nothing caught it, because nothing called
free and looked at what came back.

Each library gets one sequence, and every step is a claim:

    build            the constructor reports no error
    free             answers 1, and records no error
    free again       answers 0 -- the handle is dead and the registry knows
    error            the refusal is recorded rather than swallowed
    errormsg$        says something about it
    strerror$(code)  names the code
    clearerror       and the slot goes back to clean

The double free is the interesting one. HandleRegistry exists so that a pointer
a program kept after freeing is detectable rather than dereferenced, and this is
what asks it in anger, 97 times.

    python tests/gen_lifecycle_suite.py
    python tests/gen_lifecycle_suite.py --check

Writes tests/gui/09_lifecycle.bas.
"""
import os
import re
import sys
import glob
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GUI = os.path.join(ROOT, 'Libs', 'GUI')
OUT = os.path.join(ROOT, 'tests', 'gui', '09_lifecycle.bas')
SIG = re.compile(r"Lib\.Add\('([a-z0-9_]+)([#$]?)@([#n$]*)'")

#A control is built on the form; an effect or an animation attaches to a
#control, so it needs one to hang from.
def parent_of(path):
    d = os.path.dirname(path)
    return 'host#' if os.path.basename(d) in ('Effects', 'Animations') else 'f#'


def read():
    ctor, has = {}, defaultdict(set)
    for p in glob.glob(os.path.join(GUI, '**', '*.pas'), recursive=True):
        if '__history' in p:
            continue
        text = open(p, encoding='utf-8-sig', errors='replace').read()
        for name, ret, params in SIG.findall(text):
            if '_' not in name:
                if ret == '#' and params == '#':
                    ctor[name] = parent_of(p)
                continue
            lib, tail = name.split('_', 1)
            if tail in ('free', 'error', 'errormsg', 'strerror', 'clearerror'):
                has[lib].add(tail)
    return ctor, has


def main():
    ctor, has = read()
    need = {'free', 'error', 'errormsg', 'strerror', 'clearerror'}
    libs = sorted(l for l in ctor if need <= has[l])

    out = [
        'rem ---------------------------------------------------------------',
        'rem Build it, free it, free it again, and read the error out.',
        'rem',
        'rem Generated by tests/gen_lifecycle_suite.py -- edit that, not this.',
        'rem',
        'rem free, error, errormsg, strerror and clearerror were a quarter of the',
        'rem GUI surface and none of them was called by any test. They are also',
        'rem the quarter that fails silently: 25 *_free functions answered 0 on',
        'rem every call for months, with the line that set the result commented',
        'rem out, and nothing noticed because nothing looked at what came back.',
        'rem',
        'rem The second free is the point. HandleRegistry exists so a pointer kept',
        'rem after freeing is detected rather than followed, and this asks it 97',
        'rem times.',
        'rem ---------------------------------------------------------------',
        '',
        'f# = form#()',
        'host# = rectangle#(f#)',
        '',
    ]
    for lib in libs:
        p = ctor[lib]
        out += [
            'test_case("lifecycle/%s")' % lib,
            '%s_clearerror()' % lib,
            'c# = %s#(%s)' % (lib, p),
            'assert_eq(%s_error(), 0, "%s# built with no error")' % (lib, lib),
            'r = %s_free(c#)' % lib,
            'assert_eq(r, 1, "%s_free answers 1")' % lib,
            'assert_eq(%s_error(), 0, "%s_free records no error")' % (lib, lib),
            'r = %s_free(c#)' % lib,
            'assert_eq(r, 0, "a second %s_free is refused")' % lib,
            'e = %s_error()' % lib,
            'assert_true(e, "and the refusal is recorded")',
            's$ = %s_errormsg$()' % lib,
            'assert_true(len(s$), "%s_errormsg$ says something")' % lib,
            's$ = %s_strerror$(e)' % lib,
            'assert_true(len(s$), "%s_strerror$ names the code")' % lib,
            '%s_clearerror()' % lib,
            'assert_eq(%s_error(), 0, "%s_clearerror clears it")' % (lib, lib),
            '',
        ]

    text = '\n'.join(out)
    rel = os.path.relpath(OUT, ROOT).replace(os.sep, '/')
    if '--check' in sys.argv:
        if not os.path.isfile(OUT):
            print('  %s is missing; run this without --check' % rel)
            return 1
        have = open(OUT, encoding='utf-8', newline='').read()
        if have.replace(chr(13) + chr(10), chr(10)) != text:
            print('  %s is not what its generator produces now' % rel)
            print('  run: python tests/gen_lifecycle_suite.py')
            return 1
        print('ok  %s matches its generator, %d library(ies)' % (rel, len(libs)))
        return 0

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    #eight per library, and counted rather than multiplied by a number
    #somebody remembered: the first version of this line said nine.
    n = sum(1 for line in out if line.startswith('assert_'))
    print('%s: %d libraries, %d assertions' % (rel, len(libs), n))
    return 0


if __name__ == '__main__':
    sys.exit(main())
