"""
Generates tests/gui/03_effects.bas from the effect libraries.

The descriptors (BASIC prefix, FMX class, properties and their types) are
extracted from the units themselves, and the generated suite checks them
against the current code. That validates the descriptors before any attempt
to regenerate the units from them.

Usage:  python tests/gen_effects_suite.py
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
EFFECTS = ROOT / "Libs" / "GUI" / "Effects"
OUT = ROOT / "tests" / "gui" / "03_effects.bas"

# A round trip through an FMX Single property is not exact: several units
# convert scale (progress stores 0..100 and returns 0..1), and the pair of
# conversions loses precision. The tolerance absorbs that noise while still
# catching the error that matters when regenerating -- a getter and a setter
# wired to different properties, which returns a completely different value.
TOL = "0.001"


def descriptors():
    out = []
    for p in sorted(EFFECTS.glob("*.pas")):
        t = p.read_text(encoding="utf-8-sig", errors="surrogateescape")
        sigs = re.findall(r"\.Add\('([^']+)'", t)
        prefix = None
        for s in sigs:
            m = re.match(r"^([a-z0-9]+)#@#$", s)
            if m:
                prefix = m.group(1)
                break
        if not prefix:
            print(f"  ! {p.name}: no constructor shaped <name>#(parent#), skipped")
            continue
        props = {}
        for s in sigs:
            m = re.match(rf"^{prefix}_(\w+)#@#([n$#])$", s)
            if m and m.group(1) not in ("enabled", "trigger"):
                props[m.group(1)] = m.group(2)
        out.append({"unit": p.stem, "prefix": prefix, "props": props})
    return out


def main():
    descs = descriptors()
    L = [
        "rem ---------------------------------------------------------------",
        "rem GENERATED by tests/gen_effects_suite.py from the 64 effect units.",
        "rem Do not edit by hand.",
        "rem",
        "rem For each effect: create it, check it reported no error, and do an",
        "rem identity round trip on every numeric property (read, write the same",
        "rem value back, read again). That catches a getter and a setter wired to",
        "rem different properties, which is the failure mode when regenerating",
        "rem these units, without depending on a valid range for each property.",
        "rem ---------------------------------------------------------------",
        "",
        "f# = form#()",
        "host# = rectangle#(f#)",
        "",
    ]
    n = 0
    for d in descs:
        pre = d["prefix"]
        L += [f'test_case("effects/{pre}")',
              f"{pre}_clearerror()",
              f"e# = {pre}#(host#)",
              f'assert_eq({pre}_error(), 0, "{pre}# created with no error")']
        n += 1
        for prop, kind in d["props"].items():
            if kind != "n":
                continue
            L += [f"v = {pre}_{prop}(e#)",
                  f"{pre}_{prop}#(e#, v)",
                  f'assert_near({pre}_{prop}(e#), v, {TOL}, "{pre}_{prop} round-trip")']
            n += 1
        L += [f"{pre}_enabled#(e#, 1)",
              f'assert_eq({pre}_enabled(e#), 1, "{pre}_enabled on")',
              f"{pre}_enabled#(e#, 0)",
              f'assert_eq({pre}_enabled(e#), 0, "{pre}_enabled off")',
              ""]
        n += 2
    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {n} assertions over {len(descs)} effects")


if __name__ == "__main__":
    main()
