rem ---------------------------------------------------------------
rem GENERATED by tools/gen-doc-examples.py -- do not edit by hand.
rem
rem Every line below is a claim the documentation makes about what a
rem function returns, typed back into the interpreter. The pages state
rem these as `expr` -> `value`; only the self-contained ones are here,
rem since an example over a variable needs state the page never gave.
rem
rem This exists because string$(3, "ab") was documented as "ababab"
rem for as long as the page did, and it does not even compile.
rem ---------------------------------------------------------------

test_case("docs/worked-examples")
assert_eq(len("Hello"), 5, "New docs/Plan9Basic User Guide v1.0.md says len('Hello')")
assert_eq(left$("Hello", 3), "Hel", "New docs/Plan9Basic User Guide v1.0.md says left$('Hello', 3)")
assert_eq(right$("Hello", 2), "lo", "New docs/Plan9Basic User Guide v1.0.md says right$('Hello', 2)")
assert_eq(mid$("Hello", 1, 3), "ell", "New docs/Plan9Basic User Guide v1.0.md says mid$('Hello', 1, 3)")
assert_eq(ucase$("Hello"), "HELLO", "New docs/Plan9Basic User Guide v1.0.md says ucase$('Hello')")
assert_eq(lcase$("Hello"), "hello", "New docs/Plan9Basic User Guide v1.0.md says lcase$('Hello')")
assert_eq(trim$("  Hi  "), "Hi", "New docs/Plan9Basic User Guide v1.0.md says trim$('  Hi  ')")
assert_eq(ltrim$("  Hi"), "Hi", "New docs/Plan9Basic User Guide v1.0.md says ltrim$('  Hi')")
assert_eq(rtrim$("Hi  "), "Hi", "New docs/Plan9Basic User Guide v1.0.md says rtrim$('Hi  ')")
assert_eq(str$(42), "42", "New docs/Plan9Basic User Guide v1.0.md says str$(42)")
assert_eq(val("42"), 42, "New docs/Plan9Basic User Guide v1.0.md says val('42')")
assert_eq(chr$(65), "A", "New docs/Plan9Basic User Guide v1.0.md says chr$(65)")
assert_eq(asc("A"), 65, "New docs/Plan9Basic User Guide v1.0.md says asc('A')")
assert_eq(space$(5), "     ", "New docs/Plan9Basic User Guide v1.0.md says space$(5)")
assert_eq(string$(3, 65), "AAA", "New docs/Plan9Basic User Guide v1.0.md says string$(3, 65)")
assert_eq(replacestr$("Hello", "l", "L"), "HeLLo", "New docs/Plan9Basic User Guide v1.0.md says replacestr$('Hello', 'l', 'L')")
assert_eq(replacetext$("Hello", "L", "X"), "HeXXo", "New docs/Plan9Basic User Guide v1.0.md says replacetext$('Hello', 'L', 'X')")

rem --- not asserted, awaiting a decision ---------------------------
rem instr("Hello", "ll") is documented as 3.
rem   The two-argument instr returns 1 or 0, a contains flag, not a
rem   position. Its own three-argument form does return a position --
rem   instr("Hello World", "World", 1) is 6 -- and so does instrrev. The
rem   page, the sibling and every other BASIC agree against it.
