rem ---------------------------------------------------------------
rem GERADO por tests/gen_effects_suite.py a partir das 64 unidades de
rem efeito. Nao editar a mao.
rem
rem Para cada efeito: cria, confere que nao acusou erro, e faz round-trip
rem de identidade em cada propriedade numerica (le, grava o mesmo valor,
rem le de novo). Pega getter e setter ligados a propriedades diferentes,
rem que e o modo de falha ao regerar estas unidades, sem depender de
rem faixa valida para cada propriedade.
rem ---------------------------------------------------------------

f# = form#()
host# = rectangle#(f#)

test_case("effects/affine")
affine_clearerror()
e# = affine#(host#)
assert_eq(affine_error(), 0, "affine# criou sem erro")
v = affine_centerx(e#)
affine_centerx#(e#, v)
assert_near(affine_centerx(e#), v, 0.001, "affine_centerx round-trip")
v = affine_centery(e#)
affine_centery#(e#, v)
assert_near(affine_centery(e#), v, 0.001, "affine_centery round-trip")
v = affine_rotation(e#)
affine_rotation#(e#, v)
assert_near(affine_rotation(e#), v, 0.001, "affine_rotation round-trip")
v = affine_scale(e#)
affine_scale#(e#, v)
assert_near(affine_scale(e#), v, 0.001, "affine_scale round-trip")
affine_enabled#(e#, 1)
assert_eq(affine_enabled(e#), 1, "affine_enabled ligado")
affine_enabled#(e#, 0)
assert_eq(affine_enabled(e#), 0, "affine_enabled desligado")

test_case("effects/bswirl")
bswirl_clearerror()
e# = bswirl#(host#)
assert_eq(bswirl_error(), 0, "bswirl# criou sem erro")
v = bswirl_centerx(e#)
bswirl_centerx#(e#, v)
assert_near(bswirl_centerx(e#), v, 0.001, "bswirl_centerx round-trip")
v = bswirl_centery(e#)
bswirl_centery#(e#, v)
assert_near(bswirl_centery(e#), v, 0.001, "bswirl_centery round-trip")
v = bswirl_bands(e#)
bswirl_bands#(e#, v)
assert_near(bswirl_bands(e#), v, 0.001, "bswirl_bands round-trip")
v = bswirl_strength(e#)
bswirl_strength#(e#, v)
assert_near(bswirl_strength(e#), v, 0.001, "bswirl_strength round-trip")
v = bswirl_aspect(e#)
bswirl_aspect#(e#, v)
assert_near(bswirl_aspect(e#), v, 0.001, "bswirl_aspect round-trip")
bswirl_enabled#(e#, 1)
assert_eq(bswirl_enabled(e#), 1, "bswirl_enabled ligado")
bswirl_enabled#(e#, 0)
assert_eq(bswirl_enabled(e#), 0, "bswirl_enabled desligado")

test_case("effects/bandedswirltr")
bandedswirltr_clearerror()
e# = bandedswirltr#(host#)
assert_eq(bandedswirltr_error(), 0, "bandedswirltr# criou sem erro")
v = bandedswirltr_progress(e#)
bandedswirltr_progress#(e#, v)
assert_near(bandedswirltr_progress(e#), v, 0.001, "bandedswirltr_progress round-trip")
v = bandedswirltr_strength(e#)
bandedswirltr_strength#(e#, v)
assert_near(bandedswirltr_strength(e#), v, 0.001, "bandedswirltr_strength round-trip")
v = bandedswirltr_frequency(e#)
bandedswirltr_frequency#(e#, v)
assert_near(bandedswirltr_frequency(e#), v, 0.001, "bandedswirltr_frequency round-trip")
v = bandedswirltr_centerx(e#)
bandedswirltr_centerx#(e#, v)
assert_near(bandedswirltr_centerx(e#), v, 0.001, "bandedswirltr_centerx round-trip")
v = bandedswirltr_centery(e#)
bandedswirltr_centery#(e#, v)
assert_near(bandedswirltr_centery(e#), v, 0.001, "bandedswirltr_centery round-trip")
bandedswirltr_enabled#(e#, 1)
assert_eq(bandedswirltr_enabled(e#), 1, "bandedswirltr_enabled ligado")
bandedswirltr_enabled#(e#, 0)
assert_eq(bandedswirltr_enabled(e#), 0, "bandedswirltr_enabled desligado")

test_case("effects/bands")
bands_clearerror()
e# = bands#(host#)
assert_eq(bands_error(), 0, "bands# criou sem erro")
v = bands_density(e#)
bands_density#(e#, v)
assert_near(bands_density(e#), v, 0.001, "bands_density round-trip")
v = bands_intensity(e#)
bands_intensity#(e#, v)
assert_near(bands_intensity(e#), v, 0.001, "bands_intensity round-trip")
bands_enabled#(e#, 1)
assert_eq(bands_enabled(e#), 1, "bands_enabled ligado")
bands_enabled#(e#, 0)
assert_eq(bands_enabled(e#), 0, "bands_enabled desligado")

test_case("effects/bevel")
bevel_clearerror()
e# = bevel#(host#)
assert_eq(bevel_error(), 0, "bevel# criou sem erro")
v = bevel_direction(e#)
bevel_direction#(e#, v)
assert_near(bevel_direction(e#), v, 0.001, "bevel_direction round-trip")
v = bevel_size(e#)
bevel_size#(e#, v)
assert_near(bevel_size(e#), v, 0.001, "bevel_size round-trip")
bevel_enabled#(e#, 1)
assert_eq(bevel_enabled(e#), 1, "bevel_enabled ligado")
bevel_enabled#(e#, 0)
assert_eq(bevel_enabled(e#), 0, "bevel_enabled desligado")

test_case("effects/blindtrans")
blindtrans_clearerror()
e# = blindtrans#(host#)
assert_eq(blindtrans_error(), 0, "blindtrans# criou sem erro")
v = blindtrans_progress(e#)
blindtrans_progress#(e#, v)
assert_near(blindtrans_progress(e#), v, 0.001, "blindtrans_progress round-trip")
v = blindtrans_numblinds(e#)
blindtrans_numblinds#(e#, v)
assert_near(blindtrans_numblinds(e#), v, 0.001, "blindtrans_numblinds round-trip")
blindtrans_enabled#(e#, 1)
assert_eq(blindtrans_enabled(e#), 1, "blindtrans_enabled ligado")
blindtrans_enabled#(e#, 0)
assert_eq(blindtrans_enabled(e#), 0, "blindtrans_enabled desligado")

test_case("effects/bloodtrans")
bloodtrans_clearerror()
e# = bloodtrans#(host#)
assert_eq(bloodtrans_error(), 0, "bloodtrans# criou sem erro")
v = bloodtrans_progress(e#)
bloodtrans_progress#(e#, v)
assert_near(bloodtrans_progress(e#), v, 0.001, "bloodtrans_progress round-trip")
v = bloodtrans_randomseed(e#)
bloodtrans_randomseed#(e#, v)
assert_near(bloodtrans_randomseed(e#), v, 0.001, "bloodtrans_randomseed round-trip")
bloodtrans_enabled#(e#, 1)
assert_eq(bloodtrans_enabled(e#), 1, "bloodtrans_enabled ligado")
bloodtrans_enabled#(e#, 0)
assert_eq(bloodtrans_enabled(e#), 0, "bloodtrans_enabled desligado")

test_case("effects/bloom")
bloom_clearerror()
e# = bloom#(host#)
assert_eq(bloom_error(), 0, "bloom# criou sem erro")
v = bloom_bloomintensity(e#)
bloom_bloomintensity#(e#, v)
assert_near(bloom_bloomintensity(e#), v, 0.001, "bloom_bloomintensity round-trip")
v = bloom_baseintensity(e#)
bloom_baseintensity#(e#, v)
assert_near(bloom_baseintensity(e#), v, 0.001, "bloom_baseintensity round-trip")
v = bloom_bloomsaturation(e#)
bloom_bloomsaturation#(e#, v)
assert_near(bloom_bloomsaturation(e#), v, 0.001, "bloom_bloomsaturation round-trip")
v = bloom_basesaturation(e#)
bloom_basesaturation#(e#, v)
assert_near(bloom_basesaturation(e#), v, 0.001, "bloom_basesaturation round-trip")
bloom_enabled#(e#, 1)
assert_eq(bloom_enabled(e#), 1, "bloom_enabled ligado")
bloom_enabled#(e#, 0)
assert_eq(bloom_enabled(e#), 0, "bloom_enabled desligado")

test_case("effects/blur")
blur_clearerror()
e# = blur#(host#)
assert_eq(blur_error(), 0, "blur# criou sem erro")
v = blur_softness(e#)
blur_softness#(e#, v)
assert_near(blur_softness(e#), v, 0.001, "blur_softness round-trip")
blur_enabled#(e#, 1)
assert_eq(blur_enabled(e#), 1, "blur_enabled ligado")
blur_enabled#(e#, 0)
assert_eq(blur_enabled(e#), 0, "blur_enabled desligado")

test_case("effects/blurtrans")
blurtrans_clearerror()
e# = blurtrans#(host#)
assert_eq(blurtrans_error(), 0, "blurtrans# criou sem erro")
v = blurtrans_progress(e#)
blurtrans_progress#(e#, v)
assert_near(blurtrans_progress(e#), v, 0.001, "blurtrans_progress round-trip")
blurtrans_enabled#(e#, 1)
assert_eq(blurtrans_enabled(e#), 1, "blurtrans_enabled ligado")
blurtrans_enabled#(e#, 0)
assert_eq(blurtrans_enabled(e#), 0, "blurtrans_enabled desligado")

test_case("effects/boxblur")
boxblur_clearerror()
e# = boxblur#(host#)
assert_eq(boxblur_error(), 0, "boxblur# criou sem erro")
v = boxblur_bluramount(e#)
boxblur_bluramount#(e#, v)
assert_near(boxblur_bluramount(e#), v, 0.001, "boxblur_bluramount round-trip")
boxblur_enabled#(e#, 1)
assert_eq(boxblur_enabled(e#), 1, "boxblur_enabled ligado")
boxblur_enabled#(e#, 0)
assert_eq(boxblur_enabled(e#), 0, "boxblur_enabled desligado")

test_case("effects/brighttrans")
brighttrans_clearerror()
e# = brighttrans#(host#)
assert_eq(brighttrans_error(), 0, "brighttrans# criou sem erro")
v = brighttrans_progress(e#)
brighttrans_progress#(e#, v)
assert_near(brighttrans_progress(e#), v, 0.001, "brighttrans_progress round-trip")
brighttrans_enabled#(e#, 1)
assert_eq(brighttrans_enabled(e#), 1, "brighttrans_enabled ligado")
brighttrans_enabled#(e#, 0)
assert_eq(brighttrans_enabled(e#), 0, "brighttrans_enabled desligado")

test_case("effects/circletrans")
circletrans_clearerror()
e# = circletrans#(host#)
assert_eq(circletrans_error(), 0, "circletrans# criou sem erro")
v = circletrans_progress(e#)
circletrans_progress#(e#, v)
assert_near(circletrans_progress(e#), v, 0.001, "circletrans_progress round-trip")
v = circletrans_fuzzy(e#)
circletrans_fuzzy#(e#, v)
assert_near(circletrans_fuzzy(e#), v, 0.001, "circletrans_fuzzy round-trip")
v = circletrans_circlesize(e#)
circletrans_circlesize#(e#, v)
assert_near(circletrans_circlesize(e#), v, 0.001, "circletrans_circlesize round-trip")
circletrans_enabled#(e#, 1)
assert_eq(circletrans_enabled(e#), 1, "circletrans_enabled ligado")
circletrans_enabled#(e#, 0)
assert_eq(circletrans_enabled(e#), 0, "circletrans_enabled desligado")

test_case("effects/colorkey")
colorkey_clearerror()
e# = colorkey#(host#)
assert_eq(colorkey_error(), 0, "colorkey# criou sem erro")
v = colorkey_tolerance(e#)
colorkey_tolerance#(e#, v)
assert_near(colorkey_tolerance(e#), v, 0.001, "colorkey_tolerance round-trip")
colorkey_enabled#(e#, 1)
assert_eq(colorkey_enabled(e#), 1, "colorkey_enabled ligado")
colorkey_enabled#(e#, 0)
assert_eq(colorkey_enabled(e#), 0, "colorkey_enabled desligado")

test_case("effects/contrast")
contrast_clearerror()
e# = contrast#(host#)
assert_eq(contrast_error(), 0, "contrast# criou sem erro")
v = contrast_contrast(e#)
contrast_contrast#(e#, v)
assert_near(contrast_contrast(e#), v, 0.001, "contrast_contrast round-trip")
v = contrast_brightness(e#)
contrast_brightness#(e#, v)
assert_near(contrast_brightness(e#), v, 0.001, "contrast_brightness round-trip")
contrast_enabled#(e#, 1)
assert_eq(contrast_enabled(e#), 1, "contrast_enabled ligado")
contrast_enabled#(e#, 0)
assert_eq(contrast_enabled(e#), 0, "contrast_enabled desligado")

test_case("effects/crop")
crop_clearerror()
e# = crop#(host#)
assert_eq(crop_error(), 0, "crop# criou sem erro")
v = crop_lefttopx(e#)
crop_lefttopx#(e#, v)
assert_near(crop_lefttopx(e#), v, 0.001, "crop_lefttopx round-trip")
v = crop_lefttopy(e#)
crop_lefttopy#(e#, v)
assert_near(crop_lefttopy(e#), v, 0.001, "crop_lefttopy round-trip")
v = crop_rightbottomx(e#)
crop_rightbottomx#(e#, v)
assert_near(crop_rightbottomx(e#), v, 0.001, "crop_rightbottomx round-trip")
v = crop_rightbottomy(e#)
crop_rightbottomy#(e#, v)
assert_near(crop_rightbottomy(e#), v, 0.001, "crop_rightbottomy round-trip")
crop_enabled#(e#, 1)
assert_eq(crop_enabled(e#), 1, "crop_enabled ligado")
crop_enabled#(e#, 0)
assert_eq(crop_enabled(e#), 0, "crop_enabled desligado")

test_case("effects/crumpletrans")
crumpletrans_clearerror()
e# = crumpletrans#(host#)
assert_eq(crumpletrans_error(), 0, "crumpletrans# criou sem erro")
v = crumpletrans_progress(e#)
crumpletrans_progress#(e#, v)
assert_near(crumpletrans_progress(e#), v, 0.001, "crumpletrans_progress round-trip")
v = crumpletrans_randomseed(e#)
crumpletrans_randomseed#(e#, v)
assert_near(crumpletrans_randomseed(e#), v, 0.001, "crumpletrans_randomseed round-trip")
crumpletrans_enabled#(e#, 1)
assert_eq(crumpletrans_enabled(e#), 1, "crumpletrans_enabled ligado")
crumpletrans_enabled#(e#, 0)
assert_eq(crumpletrans_enabled(e#), 0, "crumpletrans_enabled desligado")

test_case("effects/dirblur")
dirblur_clearerror()
e# = dirblur#(host#)
assert_eq(dirblur_error(), 0, "dirblur# criou sem erro")
v = dirblur_bluramount(e#)
dirblur_bluramount#(e#, v)
assert_near(dirblur_bluramount(e#), v, 0.001, "dirblur_bluramount round-trip")
v = dirblur_angle(e#)
dirblur_angle#(e#, v)
assert_near(dirblur_angle(e#), v, 0.001, "dirblur_angle round-trip")
dirblur_enabled#(e#, 1)
assert_eq(dirblur_enabled(e#), 1, "dirblur_enabled ligado")
dirblur_enabled#(e#, 0)
assert_eq(dirblur_enabled(e#), 0, "dirblur_enabled desligado")

test_case("effects/dissolvetrans")
dissolvetrans_clearerror()
e# = dissolvetrans#(host#)
assert_eq(dissolvetrans_error(), 0, "dissolvetrans# criou sem erro")
v = dissolvetrans_progress(e#)
dissolvetrans_progress#(e#, v)
assert_near(dissolvetrans_progress(e#), v, 0.001, "dissolvetrans_progress round-trip")
v = dissolvetrans_seed(e#)
dissolvetrans_seed#(e#, v)
assert_near(dissolvetrans_seed(e#), v, 0.001, "dissolvetrans_seed round-trip")
dissolvetrans_enabled#(e#, 1)
assert_eq(dissolvetrans_enabled(e#), 1, "dissolvetrans_enabled ligado")
dissolvetrans_enabled#(e#, 0)
assert_eq(dissolvetrans_enabled(e#), 0, "dissolvetrans_enabled desligado")

test_case("effects/droptrans")
droptrans_clearerror()
e# = droptrans#(host#)
assert_eq(droptrans_error(), 0, "droptrans# criou sem erro")
v = droptrans_progress(e#)
droptrans_progress#(e#, v)
assert_near(droptrans_progress(e#), v, 0.001, "droptrans_progress round-trip")
v = droptrans_randomseed(e#)
droptrans_randomseed#(e#, v)
assert_near(droptrans_randomseed(e#), v, 0.001, "droptrans_randomseed round-trip")
droptrans_enabled#(e#, 1)
assert_eq(droptrans_enabled(e#), 1, "droptrans_enabled ligado")
droptrans_enabled#(e#, 0)
assert_eq(droptrans_enabled(e#), 0, "droptrans_enabled desligado")

test_case("effects/emboss")
emboss_clearerror()
e# = emboss#(host#)
assert_eq(emboss_error(), 0, "emboss# criou sem erro")
v = emboss_amount(e#)
emboss_amount#(e#, v)
assert_near(emboss_amount(e#), v, 0.001, "emboss_amount round-trip")
v = emboss_width(e#)
emboss_width#(e#, v)
assert_near(emboss_width(e#), v, 0.001, "emboss_width round-trip")
emboss_enabled#(e#, 1)
assert_eq(emboss_enabled(e#), 1, "emboss_enabled ligado")
emboss_enabled#(e#, 0)
assert_eq(emboss_enabled(e#), 0, "emboss_enabled desligado")

test_case("effects/fadetrans")
fadetrans_clearerror()
e# = fadetrans#(host#)
assert_eq(fadetrans_error(), 0, "fadetrans# criou sem erro")
v = fadetrans_progress(e#)
fadetrans_progress#(e#, v)
assert_near(fadetrans_progress(e#), v, 0.001, "fadetrans_progress round-trip")
fadetrans_enabled#(e#, 1)
assert_eq(fadetrans_enabled(e#), 1, "fadetrans_enabled ligado")
fadetrans_enabled#(e#, 0)
assert_eq(fadetrans_enabled(e#), 0, "fadetrans_enabled desligado")

test_case("effects/fill")
fill_clearerror()
e# = fill#(host#)
assert_eq(fill_error(), 0, "fill# criou sem erro")
v = fill_color(e#)
fill_color#(e#, v)
assert_near(fill_color(e#), v, 0.001, "fill_color round-trip")
fill_enabled#(e#, 1)
assert_eq(fill_enabled(e#), 1, "fill_enabled ligado")
fill_enabled#(e#, 0)
assert_eq(fill_enabled(e#), 0, "fill_enabled desligado")

test_case("effects/fillrgb")
fillrgb_clearerror()
e# = fillrgb#(host#)
assert_eq(fillrgb_error(), 0, "fillrgb# criou sem erro")
v = fillrgb_color(e#)
fillrgb_color#(e#, v)
assert_near(fillrgb_color(e#), v, 0.001, "fillrgb_color round-trip")
fillrgb_enabled#(e#, 1)
assert_eq(fillrgb_enabled(e#), 1, "fillrgb_enabled ligado")
fillrgb_enabled#(e#, 0)
assert_eq(fillrgb_enabled(e#), 0, "fillrgb_enabled desligado")

test_case("effects/gaussblur")
gaussblur_clearerror()
e# = gaussblur#(host#)
assert_eq(gaussblur_error(), 0, "gaussblur# criou sem erro")
v = gaussblur_bluramount(e#)
gaussblur_bluramount#(e#, v)
assert_near(gaussblur_bluramount(e#), v, 0.001, "gaussblur_bluramount round-trip")
gaussblur_enabled#(e#, 1)
assert_eq(gaussblur_enabled(e#), 1, "gaussblur_enabled ligado")
gaussblur_enabled#(e#, 0)
assert_eq(gaussblur_enabled(e#), 0, "gaussblur_enabled desligado")

test_case("effects/gloom")
gloom_clearerror()
e# = gloom#(host#)
assert_eq(gloom_error(), 0, "gloom# criou sem erro")
v = gloom_gloomintensity(e#)
gloom_gloomintensity#(e#, v)
assert_near(gloom_gloomintensity(e#), v, 0.001, "gloom_gloomintensity round-trip")
v = gloom_baseintensity(e#)
gloom_baseintensity#(e#, v)
assert_near(gloom_baseintensity(e#), v, 0.001, "gloom_baseintensity round-trip")
v = gloom_gloomsaturation(e#)
gloom_gloomsaturation#(e#, v)
assert_near(gloom_gloomsaturation(e#), v, 0.001, "gloom_gloomsaturation round-trip")
v = gloom_basesaturation(e#)
gloom_basesaturation#(e#, v)
assert_near(gloom_basesaturation(e#), v, 0.001, "gloom_basesaturation round-trip")
gloom_enabled#(e#, 1)
assert_eq(gloom_enabled(e#), 1, "gloom_enabled ligado")
gloom_enabled#(e#, 0)
assert_eq(gloom_enabled(e#), 0, "gloom_enabled desligado")

test_case("effects/glow")
glow_clearerror()
e# = glow#(host#)
assert_eq(glow_error(), 0, "glow# criou sem erro")
v = glow_softness(e#)
glow_softness#(e#, v)
assert_near(glow_softness(e#), v, 0.001, "glow_softness round-trip")
v = glow_opacity(e#)
glow_opacity#(e#, v)
assert_near(glow_opacity(e#), v, 0.001, "glow_opacity round-trip")
glow_enabled#(e#, 1)
assert_eq(glow_enabled(e#), 1, "glow_enabled ligado")
glow_enabled#(e#, 0)
assert_eq(glow_enabled(e#), 0, "glow_enabled desligado")

test_case("effects/hueadjust")
hueadjust_clearerror()
e# = hueadjust#(host#)
assert_eq(hueadjust_error(), 0, "hueadjust# criou sem erro")
v = hueadjust_hue(e#)
hueadjust_hue#(e#, v)
assert_near(hueadjust_hue(e#), v, 0.001, "hueadjust_hue round-trip")
hueadjust_enabled#(e#, 1)
assert_eq(hueadjust_enabled(e#), 1, "hueadjust_enabled ligado")
hueadjust_enabled#(e#, 0)
assert_eq(hueadjust_enabled(e#), 0, "hueadjust_enabled desligado")

test_case("effects/innerglow")
innerglow_clearerror()
e# = innerglow#(host#)
assert_eq(innerglow_error(), 0, "innerglow# criou sem erro")
v = innerglow_softness(e#)
innerglow_softness#(e#, v)
assert_near(innerglow_softness(e#), v, 0.001, "innerglow_softness round-trip")
v = innerglow_opacity(e#)
innerglow_opacity#(e#, v)
assert_near(innerglow_opacity(e#), v, 0.001, "innerglow_opacity round-trip")
innerglow_enabled#(e#, 1)
assert_eq(innerglow_enabled(e#), 1, "innerglow_enabled ligado")
innerglow_enabled#(e#, 0)
assert_eq(innerglow_enabled(e#), 0, "innerglow_enabled desligado")

test_case("effects/invert")
invert_clearerror()
e# = invert#(host#)
assert_eq(invert_error(), 0, "invert# criou sem erro")
invert_enabled#(e#, 1)
assert_eq(invert_enabled(e#), 1, "invert_enabled ligado")
invert_enabled#(e#, 0)
assert_eq(invert_enabled(e#), 0, "invert_enabled desligado")

test_case("effects/linetrans")
linetrans_clearerror()
e# = linetrans#(host#)
assert_eq(linetrans_error(), 0, "linetrans# criou sem erro")
v = linetrans_progress(e#)
linetrans_progress#(e#, v)
assert_near(linetrans_progress(e#), v, 0.001, "linetrans_progress round-trip")
v = linetrans_fuzzyamount(e#)
linetrans_fuzzyamount#(e#, v)
assert_near(linetrans_fuzzyamount(e#), v, 0.001, "linetrans_fuzzyamount round-trip")
v = linetrans_originx(e#)
linetrans_originx#(e#, v)
assert_near(linetrans_originx(e#), v, 0.001, "linetrans_originx round-trip")
v = linetrans_originy(e#)
linetrans_originy#(e#, v)
assert_near(linetrans_originy(e#), v, 0.001, "linetrans_originy round-trip")
linetrans_enabled#(e#, 1)
assert_eq(linetrans_enabled(e#), 1, "linetrans_enabled ligado")
linetrans_enabled#(e#, 0)
assert_eq(linetrans_enabled(e#), 0, "linetrans_enabled desligado")

test_case("effects/magnify")
magnify_clearerror()
e# = magnify#(host#)
assert_eq(magnify_error(), 0, "magnify# criou sem erro")
v = magnify_magnification(e#)
magnify_magnification#(e#, v)
assert_near(magnify_magnification(e#), v, 0.001, "magnify_magnification round-trip")
v = magnify_radius(e#)
magnify_radius#(e#, v)
assert_near(magnify_radius(e#), v, 0.001, "magnify_radius round-trip")
v = magnify_centerx(e#)
magnify_centerx#(e#, v)
assert_near(magnify_centerx(e#), v, 0.001, "magnify_centerx round-trip")
v = magnify_centery(e#)
magnify_centery#(e#, v)
assert_near(magnify_centery(e#), v, 0.001, "magnify_centery round-trip")
magnify_enabled#(e#, 1)
assert_eq(magnify_enabled(e#), 1, "magnify_enabled ligado")
magnify_enabled#(e#, 0)
assert_eq(magnify_enabled(e#), 0, "magnify_enabled desligado")

test_case("effects/magnifytrans")
magnifytrans_clearerror()
e# = magnifytrans#(host#)
assert_eq(magnifytrans_error(), 0, "magnifytrans# criou sem erro")
v = magnifytrans_progress(e#)
magnifytrans_progress#(e#, v)
assert_near(magnifytrans_progress(e#), v, 0.001, "magnifytrans_progress round-trip")
v = magnifytrans_centerx(e#)
magnifytrans_centerx#(e#, v)
assert_near(magnifytrans_centerx(e#), v, 0.001, "magnifytrans_centerx round-trip")
v = magnifytrans_centery(e#)
magnifytrans_centery#(e#, v)
assert_near(magnifytrans_centery(e#), v, 0.001, "magnifytrans_centery round-trip")
magnifytrans_enabled#(e#, 1)
assert_eq(magnifytrans_enabled(e#), 1, "magnifytrans_enabled ligado")
magnifytrans_enabled#(e#, 0)
assert_eq(magnifytrans_enabled(e#), 0, "magnifytrans_enabled desligado")

test_case("effects/mask2a")
mask2a_clearerror()
e# = mask2a#(host#)
assert_eq(mask2a_error(), 0, "mask2a# criou sem erro")
mask2a_enabled#(e#, 1)
assert_eq(mask2a_enabled(e#), 1, "mask2a_enabled ligado")
mask2a_enabled#(e#, 0)
assert_eq(mask2a_enabled(e#), 0, "mask2a_enabled desligado")

test_case("effects/monochrome")
monochrome_clearerror()
e# = monochrome#(host#)
assert_eq(monochrome_error(), 0, "monochrome# criou sem erro")
monochrome_enabled#(e#, 1)
assert_eq(monochrome_enabled(e#), 1, "monochrome_enabled ligado")
monochrome_enabled#(e#, 0)
assert_eq(monochrome_enabled(e#), 0, "monochrome_enabled desligado")

test_case("effects/blend")
blend_clearerror()
e# = blend#(host#)
assert_eq(blend_error(), 0, "blend# criou sem erro")
blend_enabled#(e#, 1)
assert_eq(blend_enabled(e#), 1, "blend_enabled ligado")
blend_enabled#(e#, 0)
assert_eq(blend_enabled(e#), 0, "blend_enabled desligado")

test_case("effects/papersketch")
papersketch_clearerror()
e# = papersketch#(host#)
assert_eq(papersketch_error(), 0, "papersketch# criou sem erro")
v = papersketch_brushsize(e#)
papersketch_brushsize#(e#, v)
assert_near(papersketch_brushsize(e#), v, 0.001, "papersketch_brushsize round-trip")
papersketch_enabled#(e#, 1)
assert_eq(papersketch_enabled(e#), 1, "papersketch_enabled ligado")
papersketch_enabled#(e#, 0)
assert_eq(papersketch_enabled(e#), 0, "papersketch_enabled desligado")

test_case("effects/pencilstroke")
pencilstroke_clearerror()
e# = pencilstroke#(host#)
assert_eq(pencilstroke_error(), 0, "pencilstroke# criou sem erro")
v = pencilstroke_brushsize(e#)
pencilstroke_brushsize#(e#, v)
assert_near(pencilstroke_brushsize(e#), v, 0.001, "pencilstroke_brushsize round-trip")
pencilstroke_enabled#(e#, 1)
assert_eq(pencilstroke_enabled(e#), 1, "pencilstroke_enabled ligado")
pencilstroke_enabled#(e#, 0)
assert_eq(pencilstroke_enabled(e#), 0, "pencilstroke_enabled desligado")

test_case("effects/persp")
persp_clearerror()
e# = persp#(host#)
assert_eq(persp_error(), 0, "persp# criou sem erro")
v = persp_topleftx(e#)
persp_topleftx#(e#, v)
assert_near(persp_topleftx(e#), v, 0.001, "persp_topleftx round-trip")
v = persp_toplefty(e#)
persp_toplefty#(e#, v)
assert_near(persp_toplefty(e#), v, 0.001, "persp_toplefty round-trip")
v = persp_toprightx(e#)
persp_toprightx#(e#, v)
assert_near(persp_toprightx(e#), v, 0.001, "persp_toprightx round-trip")
v = persp_toprighty(e#)
persp_toprighty#(e#, v)
assert_near(persp_toprighty(e#), v, 0.001, "persp_toprighty round-trip")
v = persp_bottomrightx(e#)
persp_bottomrightx#(e#, v)
assert_near(persp_bottomrightx(e#), v, 0.001, "persp_bottomrightx round-trip")
v = persp_bottomrighty(e#)
persp_bottomrighty#(e#, v)
assert_near(persp_bottomrighty(e#), v, 0.001, "persp_bottomrighty round-trip")
v = persp_bottomleftx(e#)
persp_bottomleftx#(e#, v)
assert_near(persp_bottomleftx(e#), v, 0.001, "persp_bottomleftx round-trip")
v = persp_bottomlefty(e#)
persp_bottomlefty#(e#, v)
assert_near(persp_bottomlefty(e#), v, 0.001, "persp_bottomlefty round-trip")
persp_enabled#(e#, 1)
assert_eq(persp_enabled(e#), 1, "persp_enabled ligado")
persp_enabled#(e#, 0)
assert_eq(persp_enabled(e#), 0, "persp_enabled desligado")

test_case("effects/pinch")
pinch_clearerror()
e# = pinch#(host#)
assert_eq(pinch_error(), 0, "pinch# criou sem erro")
v = pinch_centerx(e#)
pinch_centerx#(e#, v)
assert_near(pinch_centerx(e#), v, 0.001, "pinch_centerx round-trip")
v = pinch_centery(e#)
pinch_centery#(e#, v)
assert_near(pinch_centery(e#), v, 0.001, "pinch_centery round-trip")
v = pinch_radius(e#)
pinch_radius#(e#, v)
assert_near(pinch_radius(e#), v, 0.001, "pinch_radius round-trip")
v = pinch_strength(e#)
pinch_strength#(e#, v)
assert_near(pinch_strength(e#), v, 0.001, "pinch_strength round-trip")
v = pinch_aspect(e#)
pinch_aspect#(e#, v)
assert_near(pinch_aspect(e#), v, 0.001, "pinch_aspect round-trip")
pinch_enabled#(e#, 1)
assert_eq(pinch_enabled(e#), 1, "pinch_enabled ligado")
pinch_enabled#(e#, 0)
assert_eq(pinch_enabled(e#), 0, "pinch_enabled desligado")

test_case("effects/pixelate")
pixelate_clearerror()
e# = pixelate#(host#)
assert_eq(pixelate_error(), 0, "pixelate# criou sem erro")
v = pixelate_blockcount(e#)
pixelate_blockcount#(e#, v)
assert_near(pixelate_blockcount(e#), v, 0.001, "pixelate_blockcount round-trip")
pixelate_enabled#(e#, 1)
assert_eq(pixelate_enabled(e#), 1, "pixelate_enabled ligado")
pixelate_enabled#(e#, 0)
assert_eq(pixelate_enabled(e#), 0, "pixelate_enabled desligado")

test_case("effects/pixelatetrans")
pixelatetrans_clearerror()
e# = pixelatetrans#(host#)
assert_eq(pixelatetrans_error(), 0, "pixelatetrans# criou sem erro")
v = pixelatetrans_progress(e#)
pixelatetrans_progress#(e#, v)
assert_near(pixelatetrans_progress(e#), v, 0.001, "pixelatetrans_progress round-trip")
pixelatetrans_enabled#(e#, 1)
assert_eq(pixelatetrans_enabled(e#), 1, "pixelatetrans_enabled ligado")
pixelatetrans_enabled#(e#, 0)
assert_eq(pixelatetrans_enabled(e#), 0, "pixelatetrans_enabled desligado")

test_case("effects/radblur")
radblur_clearerror()
e# = radblur#(host#)
assert_eq(radblur_error(), 0, "radblur# criou sem erro")
v = radblur_bluramount(e#)
radblur_bluramount#(e#, v)
assert_near(radblur_bluramount(e#), v, 0.001, "radblur_bluramount round-trip")
v = radblur_centerx(e#)
radblur_centerx#(e#, v)
assert_near(radblur_centerx(e#), v, 0.001, "radblur_centerx round-trip")
v = radblur_centery(e#)
radblur_centery#(e#, v)
assert_near(radblur_centery(e#), v, 0.001, "radblur_centery round-trip")
radblur_enabled#(e#, 1)
assert_eq(radblur_enabled(e#), 1, "radblur_enabled ligado")
radblur_enabled#(e#, 0)
assert_eq(radblur_enabled(e#), 0, "radblur_enabled desligado")

test_case("effects/reflection")
reflection_clearerror()
e# = reflection#(host#)
assert_eq(reflection_error(), 0, "reflection# criou sem erro")
v = reflection_length(e#)
reflection_length#(e#, v)
assert_near(reflection_length(e#), v, 0.001, "reflection_length round-trip")
v = reflection_opacity(e#)
reflection_opacity#(e#, v)
assert_near(reflection_opacity(e#), v, 0.001, "reflection_opacity round-trip")
v = reflection_offset(e#)
reflection_offset#(e#, v)
assert_near(reflection_offset(e#), v, 0.001, "reflection_offset round-trip")
reflection_enabled#(e#, 1)
assert_eq(reflection_enabled(e#), 1, "reflection_enabled ligado")
reflection_enabled#(e#, 0)
assert_eq(reflection_enabled(e#), 0, "reflection_enabled desligado")

test_case("effects/ripple")
ripple_clearerror()
e# = ripple#(host#)
assert_eq(ripple_error(), 0, "ripple# criou sem erro")
v = ripple_amplitude(e#)
ripple_amplitude#(e#, v)
assert_near(ripple_amplitude(e#), v, 0.001, "ripple_amplitude round-trip")
v = ripple_frequency(e#)
ripple_frequency#(e#, v)
assert_near(ripple_frequency(e#), v, 0.001, "ripple_frequency round-trip")
v = ripple_phase(e#)
ripple_phase#(e#, v)
assert_near(ripple_phase(e#), v, 0.001, "ripple_phase round-trip")
v = ripple_aspectratio(e#)
ripple_aspectratio#(e#, v)
assert_near(ripple_aspectratio(e#), v, 0.001, "ripple_aspectratio round-trip")
v = ripple_centerx(e#)
ripple_centerx#(e#, v)
assert_near(ripple_centerx(e#), v, 0.001, "ripple_centerx round-trip")
v = ripple_centery(e#)
ripple_centery#(e#, v)
assert_near(ripple_centery(e#), v, 0.001, "ripple_centery round-trip")
ripple_enabled#(e#, 1)
assert_eq(ripple_enabled(e#), 1, "ripple_enabled ligado")
ripple_enabled#(e#, 0)
assert_eq(ripple_enabled(e#), 0, "ripple_enabled desligado")

test_case("effects/rippletrans")
rippletrans_clearerror()
e# = rippletrans#(host#)
assert_eq(rippletrans_error(), 0, "rippletrans# criou sem erro")
v = rippletrans_progress(e#)
rippletrans_progress#(e#, v)
assert_near(rippletrans_progress(e#), v, 0.001, "rippletrans_progress round-trip")
rippletrans_enabled#(e#, 1)
assert_eq(rippletrans_enabled(e#), 1, "rippletrans_enabled ligado")
rippletrans_enabled#(e#, 0)
assert_eq(rippletrans_enabled(e#), 0, "rippletrans_enabled desligado")

test_case("effects/rotcrumpletrans")
rotcrumpletrans_clearerror()
e# = rotcrumpletrans#(host#)
assert_eq(rotcrumpletrans_error(), 0, "rotcrumpletrans# criou sem erro")
v = rotcrumpletrans_progress(e#)
rotcrumpletrans_progress#(e#, v)
assert_near(rotcrumpletrans_progress(e#), v, 0.001, "rotcrumpletrans_progress round-trip")
v = rotcrumpletrans_randomseed(e#)
rotcrumpletrans_randomseed#(e#, v)
assert_near(rotcrumpletrans_randomseed(e#), v, 0.001, "rotcrumpletrans_randomseed round-trip")
rotcrumpletrans_enabled#(e#, 1)
assert_eq(rotcrumpletrans_enabled(e#), 1, "rotcrumpletrans_enabled ligado")
rotcrumpletrans_enabled#(e#, 0)
assert_eq(rotcrumpletrans_enabled(e#), 0, "rotcrumpletrans_enabled desligado")

test_case("effects/saturatrans")
saturatrans_clearerror()
e# = saturatrans#(host#)
assert_eq(saturatrans_error(), 0, "saturatrans# criou sem erro")
v = saturatrans_progress(e#)
saturatrans_progress#(e#, v)
assert_near(saturatrans_progress(e#), v, 0.001, "saturatrans_progress round-trip")
saturatrans_enabled#(e#, 1)
assert_eq(saturatrans_enabled(e#), 1, "saturatrans_enabled ligado")
saturatrans_enabled#(e#, 0)
assert_eq(saturatrans_enabled(e#), 0, "saturatrans_enabled desligado")

test_case("effects/sepia")
sepia_clearerror()
e# = sepia#(host#)
assert_eq(sepia_error(), 0, "sepia# criou sem erro")
v = sepia_amount(e#)
sepia_amount#(e#, v)
assert_near(sepia_amount(e#), v, 0.001, "sepia_amount round-trip")
sepia_enabled#(e#, 1)
assert_eq(sepia_enabled(e#), 1, "sepia_enabled ligado")
sepia_enabled#(e#, 0)
assert_eq(sepia_enabled(e#), 0, "sepia_enabled desligado")

test_case("effects/shadow")
shadow_clearerror()
e# = shadow#(host#)
assert_eq(shadow_error(), 0, "shadow# criou sem erro")
v = shadow_distance(e#)
shadow_distance#(e#, v)
assert_near(shadow_distance(e#), v, 0.001, "shadow_distance round-trip")
v = shadow_direction(e#)
shadow_direction#(e#, v)
assert_near(shadow_direction(e#), v, 0.001, "shadow_direction round-trip")
v = shadow_softness(e#)
shadow_softness#(e#, v)
assert_near(shadow_softness(e#), v, 0.001, "shadow_softness round-trip")
v = shadow_opacity(e#)
shadow_opacity#(e#, v)
assert_near(shadow_opacity(e#), v, 0.001, "shadow_opacity round-trip")
shadow_enabled#(e#, 1)
assert_eq(shadow_enabled(e#), 1, "shadow_enabled ligado")
shadow_enabled#(e#, 0)
assert_eq(shadow_enabled(e#), 0, "shadow_enabled desligado")

test_case("effects/shapetrans")
shapetrans_clearerror()
e# = shapetrans#(host#)
assert_eq(shapetrans_error(), 0, "shapetrans# criou sem erro")
v = shapetrans_progress(e#)
shapetrans_progress#(e#, v)
assert_near(shapetrans_progress(e#), v, 0.001, "shapetrans_progress round-trip")
v = shapetrans_randomseed(e#)
shapetrans_randomseed#(e#, v)
assert_near(shapetrans_randomseed(e#), v, 0.001, "shapetrans_randomseed round-trip")
shapetrans_enabled#(e#, 1)
assert_eq(shapetrans_enabled(e#), 1, "shapetrans_enabled ligado")
shapetrans_enabled#(e#, 0)
assert_eq(shapetrans_enabled(e#), 0, "shapetrans_enabled desligado")

test_case("effects/sharpen")
sharpen_clearerror()
e# = sharpen#(host#)
assert_eq(sharpen_error(), 0, "sharpen# criou sem erro")
v = sharpen_amount(e#)
sharpen_amount#(e#, v)
assert_near(sharpen_amount(e#), v, 0.001, "sharpen_amount round-trip")
sharpen_enabled#(e#, 1)
assert_eq(sharpen_enabled(e#), 1, "sharpen_enabled ligado")
sharpen_enabled#(e#, 0)
assert_eq(sharpen_enabled(e#), 0, "sharpen_enabled desligado")

test_case("effects/slidetrans")
slidetrans_clearerror()
e# = slidetrans#(host#)
assert_eq(slidetrans_error(), 0, "slidetrans# criou sem erro")
v = slidetrans_progress(e#)
slidetrans_progress#(e#, v)
assert_near(slidetrans_progress(e#), v, 0.001, "slidetrans_progress round-trip")
v = slidetrans_amountx(e#)
slidetrans_amountx#(e#, v)
assert_near(slidetrans_amountx(e#), v, 0.001, "slidetrans_amountx round-trip")
v = slidetrans_amounty(e#)
slidetrans_amounty#(e#, v)
assert_near(slidetrans_amounty(e#), v, 0.001, "slidetrans_amounty round-trip")
slidetrans_enabled#(e#, 1)
assert_eq(slidetrans_enabled(e#), 1, "slidetrans_enabled ligado")
slidetrans_enabled#(e#, 0)
assert_eq(slidetrans_enabled(e#), 0, "slidetrans_enabled desligado")

test_case("effects/smag")
smag_clearerror()
e# = smag#(host#)
assert_eq(smag_error(), 0, "smag# criou sem erro")
v = smag_centerx(e#)
smag_centerx#(e#, v)
assert_near(smag_centerx(e#), v, 0.001, "smag_centerx round-trip")
v = smag_centery(e#)
smag_centery#(e#, v)
assert_near(smag_centery(e#), v, 0.001, "smag_centery round-trip")
v = smag_mag(e#)
smag_mag#(e#, v)
assert_near(smag_mag(e#), v, 0.001, "smag_mag round-trip")
v = smag_inner(e#)
smag_inner#(e#, v)
assert_near(smag_inner(e#), v, 0.001, "smag_inner round-trip")
v = smag_outer(e#)
smag_outer#(e#, v)
assert_near(smag_outer(e#), v, 0.001, "smag_outer round-trip")
v = smag_aspect(e#)
smag_aspect#(e#, v)
assert_near(smag_aspect(e#), v, 0.001, "smag_aspect round-trip")
smag_enabled#(e#, 1)
assert_eq(smag_enabled(e#), 1, "smag_enabled ligado")
smag_enabled#(e#, 0)
assert_eq(smag_enabled(e#), 0, "smag_enabled desligado")

test_case("effects/swipetrans")
swipetrans_clearerror()
e# = swipetrans#(host#)
assert_eq(swipetrans_error(), 0, "swipetrans# criou sem erro")
v = swipetrans_mousex(e#)
swipetrans_mousex#(e#, v)
assert_near(swipetrans_mousex(e#), v, 0.001, "swipetrans_mousex round-trip")
v = swipetrans_mousey(e#)
swipetrans_mousey#(e#, v)
assert_near(swipetrans_mousey(e#), v, 0.001, "swipetrans_mousey round-trip")
v = swipetrans_deep(e#)
swipetrans_deep#(e#, v)
assert_near(swipetrans_deep(e#), v, 0.001, "swipetrans_deep round-trip")
swipetrans_enabled#(e#, 1)
assert_eq(swipetrans_enabled(e#), 1, "swipetrans_enabled ligado")
swipetrans_enabled#(e#, 0)
assert_eq(swipetrans_enabled(e#), 0, "swipetrans_enabled desligado")

test_case("effects/swirl")
swirl_clearerror()
e# = swirl#(host#)
assert_eq(swirl_error(), 0, "swirl# criou sem erro")
v = swirl_strength(e#)
swirl_strength#(e#, v)
assert_near(swirl_strength(e#), v, 0.001, "swirl_strength round-trip")
v = swirl_centerx(e#)
swirl_centerx#(e#, v)
assert_near(swirl_centerx(e#), v, 0.001, "swirl_centerx round-trip")
v = swirl_centery(e#)
swirl_centery#(e#, v)
assert_near(swirl_centery(e#), v, 0.001, "swirl_centery round-trip")
swirl_enabled#(e#, 1)
assert_eq(swirl_enabled(e#), 1, "swirl_enabled ligado")
swirl_enabled#(e#, 0)
assert_eq(swirl_enabled(e#), 0, "swirl_enabled desligado")

test_case("effects/swirltrans")
swirltrans_clearerror()
e# = swirltrans#(host#)
assert_eq(swirltrans_error(), 0, "swirltrans# criou sem erro")
v = swirltrans_progress(e#)
swirltrans_progress#(e#, v)
assert_near(swirltrans_progress(e#), v, 0.001, "swirltrans_progress round-trip")
v = swirltrans_strength(e#)
swirltrans_strength#(e#, v)
assert_near(swirltrans_strength(e#), v, 0.001, "swirltrans_strength round-trip")
swirltrans_enabled#(e#, 1)
assert_eq(swirltrans_enabled(e#), 1, "swirltrans_enabled ligado")
swirltrans_enabled#(e#, 0)
assert_eq(swirltrans_enabled(e#), 0, "swirltrans_enabled desligado")

test_case("effects/tiler")
tiler_clearerror()
e# = tiler#(host#)
assert_eq(tiler_error(), 0, "tiler# criou sem erro")
v = tiler_vtiles(e#)
tiler_vtiles#(e#, v)
assert_near(tiler_vtiles(e#), v, 0.001, "tiler_vtiles round-trip")
v = tiler_htiles(e#)
tiler_htiles#(e#, v)
assert_near(tiler_htiles(e#), v, 0.001, "tiler_htiles round-trip")
tiler_enabled#(e#, 1)
assert_eq(tiler_enabled(e#), 1, "tiler_enabled ligado")
tiler_enabled#(e#, 0)
assert_eq(tiler_enabled(e#), 0, "tiler_enabled desligado")

test_case("effects/toon")
toon_clearerror()
e# = toon#(host#)
assert_eq(toon_error(), 0, "toon# criou sem erro")
v = toon_levels(e#)
toon_levels#(e#, v)
assert_near(toon_levels(e#), v, 0.001, "toon_levels round-trip")
toon_enabled#(e#, 1)
assert_eq(toon_enabled(e#), 1, "toon_enabled ligado")
toon_enabled#(e#, 0)
assert_eq(toon_enabled(e#), 0, "toon_enabled desligado")

test_case("effects/watertrans")
watertrans_clearerror()
e# = watertrans#(host#)
assert_eq(watertrans_error(), 0, "watertrans# criou sem erro")
v = watertrans_progress(e#)
watertrans_progress#(e#, v)
assert_near(watertrans_progress(e#), v, 0.001, "watertrans_progress round-trip")
v = watertrans_randomseed(e#)
watertrans_randomseed#(e#, v)
assert_near(watertrans_randomseed(e#), v, 0.001, "watertrans_randomseed round-trip")
watertrans_enabled#(e#, 1)
assert_eq(watertrans_enabled(e#), 1, "watertrans_enabled ligado")
watertrans_enabled#(e#, 0)
assert_eq(watertrans_enabled(e#), 0, "watertrans_enabled desligado")

test_case("effects/wave")
wave_clearerror()
e# = wave#(host#)
assert_eq(wave_error(), 0, "wave# criou sem erro")
v = wave_wavesize(e#)
wave_wavesize#(e#, v)
assert_near(wave_wavesize(e#), v, 0.001, "wave_wavesize round-trip")
v = wave_time(e#)
wave_time#(e#, v)
assert_near(wave_time(e#), v, 0.001, "wave_time round-trip")
wave_enabled#(e#, 1)
assert_eq(wave_enabled(e#), 1, "wave_enabled ligado")
wave_enabled#(e#, 0)
assert_eq(wave_enabled(e#), 0, "wave_enabled desligado")

test_case("effects/wavetrans")
wavetrans_clearerror()
e# = wavetrans#(host#)
assert_eq(wavetrans_error(), 0, "wavetrans# criou sem erro")
v = wavetrans_progress(e#)
wavetrans_progress#(e#, v)
assert_near(wavetrans_progress(e#), v, 0.001, "wavetrans_progress round-trip")
wavetrans_enabled#(e#, 1)
assert_eq(wavetrans_enabled(e#), 1, "wavetrans_enabled ligado")
wavetrans_enabled#(e#, 0)
assert_eq(wavetrans_enabled(e#), 0, "wavetrans_enabled desligado")

test_case("effects/wiggletrans")
wiggletrans_clearerror()
e# = wiggletrans#(host#)
assert_eq(wiggletrans_error(), 0, "wiggletrans# criou sem erro")
v = wiggletrans_progress(e#)
wiggletrans_progress#(e#, v)
assert_near(wiggletrans_progress(e#), v, 0.001, "wiggletrans_progress round-trip")
v = wiggletrans_randomseed(e#)
wiggletrans_randomseed#(e#, v)
assert_near(wiggletrans_randomseed(e#), v, 0.001, "wiggletrans_randomseed round-trip")
wiggletrans_enabled#(e#, 1)
assert_eq(wiggletrans_enabled(e#), 1, "wiggletrans_enabled ligado")
wiggletrans_enabled#(e#, 0)
assert_eq(wiggletrans_enabled(e#), 0, "wiggletrans_enabled desligado")

test_case("effects/wrap")
wrap_clearerror()
e# = wrap#(host#)
assert_eq(wrap_error(), 0, "wrap# criou sem erro")
v = wrap_leftstart(e#)
wrap_leftstart#(e#, v)
assert_near(wrap_leftstart(e#), v, 0.001, "wrap_leftstart round-trip")
v = wrap_leftctrl1(e#)
wrap_leftctrl1#(e#, v)
assert_near(wrap_leftctrl1(e#), v, 0.001, "wrap_leftctrl1 round-trip")
v = wrap_leftctrl2(e#)
wrap_leftctrl2#(e#, v)
assert_near(wrap_leftctrl2(e#), v, 0.001, "wrap_leftctrl2 round-trip")
v = wrap_leftend(e#)
wrap_leftend#(e#, v)
assert_near(wrap_leftend(e#), v, 0.001, "wrap_leftend round-trip")
wrap_enabled#(e#, 1)
assert_eq(wrap_enabled(e#), 1, "wrap_enabled ligado")
wrap_enabled#(e#, 0)
assert_eq(wrap_enabled(e#), 0, "wrap_enabled desligado")
