rem ---------------------------------------------------------------
rem Alignment round trip on every control.
rem
rem Each control library used to carry its own AlignToInt/AlignFromInt,
rem and those had drifted into three tiers covering 6, 7 or 20 of the
rem TAlignLayout values. A button asked for MostTop got None, silently,
rem while a rectangle got MostTop. ControlCommon now answers for all of
rem them, and this file is what keeps them answering the same way.
rem
rem Values 5, 13 and 19 are the ones the narrow tiers could not express.
rem ---------------------------------------------------------------

f# = form#()

test_case("align/arc")
c# = arc#(f#)
arc_align#(c#, 0)
assert_eq(arc_align(c#), 0, "arc None")
arc_align#(c#, 1)
assert_eq(arc_align(c#), 1, "arc Top")
arc_align#(c#, 4)
assert_eq(arc_align(c#), 4, "arc Bottom")
arc_align#(c#, 5)
assert_eq(arc_align(c#), 5, "arc MostTop")
arc_align#(c#, 9)
assert_eq(arc_align(c#), 9, "arc Client")
arc_align#(c#, 11)
assert_eq(arc_align(c#), 11, "arc Center")
arc_align#(c#, 13)
assert_eq(arc_align(c#), 13, "arc HorzCenter")
arc_align#(c#, 19)
assert_eq(arc_align(c#), 19, "arc FitRight")

test_case("align/button")
c# = button#(f#)
button_align#(c#, 0)
assert_eq(button_align(c#), 0, "button None")
button_align#(c#, 1)
assert_eq(button_align(c#), 1, "button Top")
button_align#(c#, 4)
assert_eq(button_align(c#), 4, "button Bottom")
button_align#(c#, 5)
assert_eq(button_align(c#), 5, "button MostTop")
button_align#(c#, 9)
assert_eq(button_align(c#), 9, "button Client")
button_align#(c#, 11)
assert_eq(button_align(c#), 11, "button Center")
button_align#(c#, 13)
assert_eq(button_align(c#), 13, "button HorzCenter")
button_align#(c#, 19)
assert_eq(button_align(c#), 19, "button FitRight")

test_case("align/callout")
c# = callout#(f#)
callout_align#(c#, 0)
assert_eq(callout_align(c#), 0, "callout None")
callout_align#(c#, 1)
assert_eq(callout_align(c#), 1, "callout Top")
callout_align#(c#, 4)
assert_eq(callout_align(c#), 4, "callout Bottom")
callout_align#(c#, 5)
assert_eq(callout_align(c#), 5, "callout MostTop")
callout_align#(c#, 9)
assert_eq(callout_align(c#), 9, "callout Client")
callout_align#(c#, 11)
assert_eq(callout_align(c#), 11, "callout Center")
callout_align#(c#, 13)
assert_eq(callout_align(c#), 13, "callout HorzCenter")
callout_align#(c#, 19)
assert_eq(callout_align(c#), 19, "callout FitRight")

test_case("align/checkbox")
c# = checkbox#(f#)
checkbox_align#(c#, 0)
assert_eq(checkbox_align(c#), 0, "checkbox None")
checkbox_align#(c#, 1)
assert_eq(checkbox_align(c#), 1, "checkbox Top")
checkbox_align#(c#, 4)
assert_eq(checkbox_align(c#), 4, "checkbox Bottom")
checkbox_align#(c#, 5)
assert_eq(checkbox_align(c#), 5, "checkbox MostTop")
checkbox_align#(c#, 9)
assert_eq(checkbox_align(c#), 9, "checkbox Client")
checkbox_align#(c#, 11)
assert_eq(checkbox_align(c#), 11, "checkbox Center")
checkbox_align#(c#, 13)
assert_eq(checkbox_align(c#), 13, "checkbox HorzCenter")
checkbox_align#(c#, 19)
assert_eq(checkbox_align(c#), 19, "checkbox FitRight")

test_case("align/circle")
c# = circle#(f#)
circle_align#(c#, 0)
assert_eq(circle_align(c#), 0, "circle None")
circle_align#(c#, 1)
assert_eq(circle_align(c#), 1, "circle Top")
circle_align#(c#, 4)
assert_eq(circle_align(c#), 4, "circle Bottom")
circle_align#(c#, 5)
assert_eq(circle_align(c#), 5, "circle MostTop")
circle_align#(c#, 9)
assert_eq(circle_align(c#), 9, "circle Client")
circle_align#(c#, 11)
assert_eq(circle_align(c#), 11, "circle Center")
circle_align#(c#, 13)
assert_eq(circle_align(c#), 13, "circle HorzCenter")
circle_align#(c#, 19)
assert_eq(circle_align(c#), 19, "circle FitRight")

test_case("align/combobox")
c# = combobox#(f#)
combobox_align#(c#, 0)
assert_eq(combobox_align(c#), 0, "combobox None")
combobox_align#(c#, 1)
assert_eq(combobox_align(c#), 1, "combobox Top")
combobox_align#(c#, 4)
assert_eq(combobox_align(c#), 4, "combobox Bottom")
combobox_align#(c#, 5)
assert_eq(combobox_align(c#), 5, "combobox MostTop")
combobox_align#(c#, 9)
assert_eq(combobox_align(c#), 9, "combobox Client")
combobox_align#(c#, 11)
assert_eq(combobox_align(c#), 11, "combobox Center")
combobox_align#(c#, 13)
assert_eq(combobox_align(c#), 13, "combobox HorzCenter")
combobox_align#(c#, 19)
assert_eq(combobox_align(c#), 19, "combobox FitRight")

test_case("align/edit")
c# = edit#(f#)
edit_align#(c#, 0)
assert_eq(edit_align(c#), 0, "edit None")
edit_align#(c#, 1)
assert_eq(edit_align(c#), 1, "edit Top")
edit_align#(c#, 4)
assert_eq(edit_align(c#), 4, "edit Bottom")
edit_align#(c#, 5)
assert_eq(edit_align(c#), 5, "edit MostTop")
edit_align#(c#, 9)
assert_eq(edit_align(c#), 9, "edit Client")
edit_align#(c#, 11)
assert_eq(edit_align(c#), 11, "edit Center")
edit_align#(c#, 13)
assert_eq(edit_align(c#), 13, "edit HorzCenter")
edit_align#(c#, 19)
assert_eq(edit_align(c#), 19, "edit FitRight")

test_case("align/ellipse")
c# = ellipse#(f#)
ellipse_align#(c#, 0)
assert_eq(ellipse_align(c#), 0, "ellipse None")
ellipse_align#(c#, 1)
assert_eq(ellipse_align(c#), 1, "ellipse Top")
ellipse_align#(c#, 4)
assert_eq(ellipse_align(c#), 4, "ellipse Bottom")
ellipse_align#(c#, 5)
assert_eq(ellipse_align(c#), 5, "ellipse MostTop")
ellipse_align#(c#, 9)
assert_eq(ellipse_align(c#), 9, "ellipse Client")
ellipse_align#(c#, 11)
assert_eq(ellipse_align(c#), 11, "ellipse Center")
ellipse_align#(c#, 13)
assert_eq(ellipse_align(c#), 13, "ellipse HorzCenter")
ellipse_align#(c#, 19)
assert_eq(ellipse_align(c#), 19, "ellipse FitRight")

test_case("align/image")
c# = image#(f#)
image_align#(c#, 0)
assert_eq(image_align(c#), 0, "image None")
image_align#(c#, 1)
assert_eq(image_align(c#), 1, "image Top")
image_align#(c#, 4)
assert_eq(image_align(c#), 4, "image Bottom")
image_align#(c#, 5)
assert_eq(image_align(c#), 5, "image MostTop")
image_align#(c#, 9)
assert_eq(image_align(c#), 9, "image Client")
image_align#(c#, 11)
assert_eq(image_align(c#), 11, "image Center")
image_align#(c#, 13)
assert_eq(image_align(c#), 13, "image HorzCenter")
image_align#(c#, 19)
assert_eq(image_align(c#), 19, "image FitRight")

test_case("align/label")
c# = label#(f#)
label_align#(c#, 0)
assert_eq(label_align(c#), 0, "label None")
label_align#(c#, 1)
assert_eq(label_align(c#), 1, "label Top")
label_align#(c#, 4)
assert_eq(label_align(c#), 4, "label Bottom")
label_align#(c#, 5)
assert_eq(label_align(c#), 5, "label MostTop")
label_align#(c#, 9)
assert_eq(label_align(c#), 9, "label Client")
label_align#(c#, 11)
assert_eq(label_align(c#), 11, "label Center")
label_align#(c#, 13)
assert_eq(label_align(c#), 13, "label HorzCenter")
label_align#(c#, 19)
assert_eq(label_align(c#), 19, "label FitRight")

test_case("align/layout")
c# = layout#(f#)
layout_align#(c#, 0)
assert_eq(layout_align(c#), 0, "layout None")
layout_align#(c#, 1)
assert_eq(layout_align(c#), 1, "layout Top")
layout_align#(c#, 4)
assert_eq(layout_align(c#), 4, "layout Bottom")
layout_align#(c#, 5)
assert_eq(layout_align(c#), 5, "layout MostTop")
layout_align#(c#, 9)
assert_eq(layout_align(c#), 9, "layout Client")
layout_align#(c#, 11)
assert_eq(layout_align(c#), 11, "layout Center")
layout_align#(c#, 13)
assert_eq(layout_align(c#), 13, "layout HorzCenter")
layout_align#(c#, 19)
assert_eq(layout_align(c#), 19, "layout FitRight")

test_case("align/line")
c# = line#(f#)
line_align#(c#, 0)
assert_eq(line_align(c#), 0, "line None")
line_align#(c#, 1)
assert_eq(line_align(c#), 1, "line Top")
line_align#(c#, 4)
assert_eq(line_align(c#), 4, "line Bottom")
line_align#(c#, 5)
assert_eq(line_align(c#), 5, "line MostTop")
line_align#(c#, 9)
assert_eq(line_align(c#), 9, "line Client")
line_align#(c#, 11)
assert_eq(line_align(c#), 11, "line Center")
line_align#(c#, 13)
assert_eq(line_align(c#), 13, "line HorzCenter")
line_align#(c#, 19)
assert_eq(line_align(c#), 19, "line FitRight")

test_case("align/listbox")
c# = listbox#(f#)
listbox_align#(c#, 0)
assert_eq(listbox_align(c#), 0, "listbox None")
listbox_align#(c#, 1)
assert_eq(listbox_align(c#), 1, "listbox Top")
listbox_align#(c#, 4)
assert_eq(listbox_align(c#), 4, "listbox Bottom")
listbox_align#(c#, 5)
assert_eq(listbox_align(c#), 5, "listbox MostTop")
listbox_align#(c#, 9)
assert_eq(listbox_align(c#), 9, "listbox Client")
listbox_align#(c#, 11)
assert_eq(listbox_align(c#), 11, "listbox Center")
listbox_align#(c#, 13)
assert_eq(listbox_align(c#), 13, "listbox HorzCenter")
listbox_align#(c#, 19)
assert_eq(listbox_align(c#), 19, "listbox FitRight")

test_case("align/memo")
c# = memo#(f#)
memo_align#(c#, 0)
assert_eq(memo_align(c#), 0, "memo None")
memo_align#(c#, 1)
assert_eq(memo_align(c#), 1, "memo Top")
memo_align#(c#, 4)
assert_eq(memo_align(c#), 4, "memo Bottom")
memo_align#(c#, 5)
assert_eq(memo_align(c#), 5, "memo MostTop")
memo_align#(c#, 9)
assert_eq(memo_align(c#), 9, "memo Client")
memo_align#(c#, 11)
assert_eq(memo_align(c#), 11, "memo Center")
memo_align#(c#, 13)
assert_eq(memo_align(c#), 13, "memo HorzCenter")
memo_align#(c#, 19)
assert_eq(memo_align(c#), 19, "memo FitRight")

test_case("align/panel")
c# = panel#(f#)
panel_align#(c#, 0)
assert_eq(panel_align(c#), 0, "panel None")
panel_align#(c#, 1)
assert_eq(panel_align(c#), 1, "panel Top")
panel_align#(c#, 4)
assert_eq(panel_align(c#), 4, "panel Bottom")
panel_align#(c#, 5)
assert_eq(panel_align(c#), 5, "panel MostTop")
panel_align#(c#, 9)
assert_eq(panel_align(c#), 9, "panel Client")
panel_align#(c#, 11)
assert_eq(panel_align(c#), 11, "panel Center")
panel_align#(c#, 13)
assert_eq(panel_align(c#), 13, "panel HorzCenter")
panel_align#(c#, 19)
assert_eq(panel_align(c#), 19, "panel FitRight")

test_case("align/path")
c# = path#(f#)
path_align#(c#, 0)
assert_eq(path_align(c#), 0, "path None")
path_align#(c#, 1)
assert_eq(path_align(c#), 1, "path Top")
path_align#(c#, 4)
assert_eq(path_align(c#), 4, "path Bottom")
path_align#(c#, 5)
assert_eq(path_align(c#), 5, "path MostTop")
path_align#(c#, 9)
assert_eq(path_align(c#), 9, "path Client")
path_align#(c#, 11)
assert_eq(path_align(c#), 11, "path Center")
path_align#(c#, 13)
assert_eq(path_align(c#), 13, "path HorzCenter")
path_align#(c#, 19)
assert_eq(path_align(c#), 19, "path FitRight")

test_case("align/pie")
c# = pie#(f#)
pie_align#(c#, 0)
assert_eq(pie_align(c#), 0, "pie None")
pie_align#(c#, 1)
assert_eq(pie_align(c#), 1, "pie Top")
pie_align#(c#, 4)
assert_eq(pie_align(c#), 4, "pie Bottom")
pie_align#(c#, 5)
assert_eq(pie_align(c#), 5, "pie MostTop")
pie_align#(c#, 9)
assert_eq(pie_align(c#), 9, "pie Client")
pie_align#(c#, 11)
assert_eq(pie_align(c#), 11, "pie Center")
pie_align#(c#, 13)
assert_eq(pie_align(c#), 13, "pie HorzCenter")
pie_align#(c#, 19)
assert_eq(pie_align(c#), 19, "pie FitRight")

test_case("align/progressbar")
c# = progressbar#(f#)
progressbar_align#(c#, 0)
assert_eq(progressbar_align(c#), 0, "progressbar None")
progressbar_align#(c#, 1)
assert_eq(progressbar_align(c#), 1, "progressbar Top")
progressbar_align#(c#, 4)
assert_eq(progressbar_align(c#), 4, "progressbar Bottom")
progressbar_align#(c#, 5)
assert_eq(progressbar_align(c#), 5, "progressbar MostTop")
progressbar_align#(c#, 9)
assert_eq(progressbar_align(c#), 9, "progressbar Client")
progressbar_align#(c#, 11)
assert_eq(progressbar_align(c#), 11, "progressbar Center")
progressbar_align#(c#, 13)
assert_eq(progressbar_align(c#), 13, "progressbar HorzCenter")
progressbar_align#(c#, 19)
assert_eq(progressbar_align(c#), 19, "progressbar FitRight")

test_case("align/radiobutton")
c# = radiobutton#(f#)
radiobutton_align#(c#, 0)
assert_eq(radiobutton_align(c#), 0, "radiobutton None")
radiobutton_align#(c#, 1)
assert_eq(radiobutton_align(c#), 1, "radiobutton Top")
radiobutton_align#(c#, 4)
assert_eq(radiobutton_align(c#), 4, "radiobutton Bottom")
radiobutton_align#(c#, 5)
assert_eq(radiobutton_align(c#), 5, "radiobutton MostTop")
radiobutton_align#(c#, 9)
assert_eq(radiobutton_align(c#), 9, "radiobutton Client")
radiobutton_align#(c#, 11)
assert_eq(radiobutton_align(c#), 11, "radiobutton Center")
radiobutton_align#(c#, 13)
assert_eq(radiobutton_align(c#), 13, "radiobutton HorzCenter")
radiobutton_align#(c#, 19)
assert_eq(radiobutton_align(c#), 19, "radiobutton FitRight")

test_case("align/rectangle")
c# = rectangle#(f#)
rectangle_align#(c#, 0)
assert_eq(rectangle_align(c#), 0, "rectangle None")
rectangle_align#(c#, 1)
assert_eq(rectangle_align(c#), 1, "rectangle Top")
rectangle_align#(c#, 4)
assert_eq(rectangle_align(c#), 4, "rectangle Bottom")
rectangle_align#(c#, 5)
assert_eq(rectangle_align(c#), 5, "rectangle MostTop")
rectangle_align#(c#, 9)
assert_eq(rectangle_align(c#), 9, "rectangle Client")
rectangle_align#(c#, 11)
assert_eq(rectangle_align(c#), 11, "rectangle Center")
rectangle_align#(c#, 13)
assert_eq(rectangle_align(c#), 13, "rectangle HorzCenter")
rectangle_align#(c#, 19)
assert_eq(rectangle_align(c#), 19, "rectangle FitRight")

test_case("align/roundrect")
c# = roundrect#(f#)
roundrect_align#(c#, 0)
assert_eq(roundrect_align(c#), 0, "roundrect None")
roundrect_align#(c#, 1)
assert_eq(roundrect_align(c#), 1, "roundrect Top")
roundrect_align#(c#, 4)
assert_eq(roundrect_align(c#), 4, "roundrect Bottom")
roundrect_align#(c#, 5)
assert_eq(roundrect_align(c#), 5, "roundrect MostTop")
roundrect_align#(c#, 9)
assert_eq(roundrect_align(c#), 9, "roundrect Client")
roundrect_align#(c#, 11)
assert_eq(roundrect_align(c#), 11, "roundrect Center")
roundrect_align#(c#, 13)
assert_eq(roundrect_align(c#), 13, "roundrect HorzCenter")
roundrect_align#(c#, 19)
assert_eq(roundrect_align(c#), 19, "roundrect FitRight")

test_case("align/scrollbox")
c# = scrollbox#(f#)
scrollbox_align#(c#, 0)
assert_eq(scrollbox_align(c#), 0, "scrollbox None")
scrollbox_align#(c#, 1)
assert_eq(scrollbox_align(c#), 1, "scrollbox Top")
scrollbox_align#(c#, 4)
assert_eq(scrollbox_align(c#), 4, "scrollbox Bottom")
scrollbox_align#(c#, 5)
assert_eq(scrollbox_align(c#), 5, "scrollbox MostTop")
scrollbox_align#(c#, 9)
assert_eq(scrollbox_align(c#), 9, "scrollbox Client")
scrollbox_align#(c#, 11)
assert_eq(scrollbox_align(c#), 11, "scrollbox Center")
scrollbox_align#(c#, 13)
assert_eq(scrollbox_align(c#), 13, "scrollbox HorzCenter")
scrollbox_align#(c#, 19)
assert_eq(scrollbox_align(c#), 19, "scrollbox FitRight")

test_case("align/speedbutton")
c# = speedbutton#(f#)
speedbutton_align#(c#, 0)
assert_eq(speedbutton_align(c#), 0, "speedbutton None")
speedbutton_align#(c#, 1)
assert_eq(speedbutton_align(c#), 1, "speedbutton Top")
speedbutton_align#(c#, 4)
assert_eq(speedbutton_align(c#), 4, "speedbutton Bottom")
speedbutton_align#(c#, 5)
assert_eq(speedbutton_align(c#), 5, "speedbutton MostTop")
speedbutton_align#(c#, 9)
assert_eq(speedbutton_align(c#), 9, "speedbutton Client")
speedbutton_align#(c#, 11)
assert_eq(speedbutton_align(c#), 11, "speedbutton Center")
speedbutton_align#(c#, 13)
assert_eq(speedbutton_align(c#), 13, "speedbutton HorzCenter")
speedbutton_align#(c#, 19)
assert_eq(speedbutton_align(c#), 19, "speedbutton FitRight")

test_case("align/stringgrid")
c# = stringgrid#(f#)
stringgrid_align#(c#, 0)
assert_eq(stringgrid_align(c#), 0, "stringgrid None")
stringgrid_align#(c#, 1)
assert_eq(stringgrid_align(c#), 1, "stringgrid Top")
stringgrid_align#(c#, 4)
assert_eq(stringgrid_align(c#), 4, "stringgrid Bottom")
stringgrid_align#(c#, 5)
assert_eq(stringgrid_align(c#), 5, "stringgrid MostTop")
stringgrid_align#(c#, 9)
assert_eq(stringgrid_align(c#), 9, "stringgrid Client")
stringgrid_align#(c#, 11)
assert_eq(stringgrid_align(c#), 11, "stringgrid Center")
stringgrid_align#(c#, 13)
assert_eq(stringgrid_align(c#), 13, "stringgrid HorzCenter")
stringgrid_align#(c#, 19)
assert_eq(stringgrid_align(c#), 19, "stringgrid FitRight")

test_case("align/switch")
c# = switch#(f#)
switch_align#(c#, 0)
assert_eq(switch_align(c#), 0, "switch None")
switch_align#(c#, 1)
assert_eq(switch_align(c#), 1, "switch Top")
switch_align#(c#, 4)
assert_eq(switch_align(c#), 4, "switch Bottom")
switch_align#(c#, 5)
assert_eq(switch_align(c#), 5, "switch MostTop")
switch_align#(c#, 9)
assert_eq(switch_align(c#), 9, "switch Client")
switch_align#(c#, 11)
assert_eq(switch_align(c#), 11, "switch Center")
switch_align#(c#, 13)
assert_eq(switch_align(c#), 13, "switch HorzCenter")
switch_align#(c#, 19)
assert_eq(switch_align(c#), 19, "switch FitRight")

test_case("align/trackbar")
c# = trackbar#(f#)
trackbar_align#(c#, 0)
assert_eq(trackbar_align(c#), 0, "trackbar None")
trackbar_align#(c#, 1)
assert_eq(trackbar_align(c#), 1, "trackbar Top")
trackbar_align#(c#, 4)
assert_eq(trackbar_align(c#), 4, "trackbar Bottom")
trackbar_align#(c#, 5)
assert_eq(trackbar_align(c#), 5, "trackbar MostTop")
trackbar_align#(c#, 9)
assert_eq(trackbar_align(c#), 9, "trackbar Client")
trackbar_align#(c#, 11)
assert_eq(trackbar_align(c#), 11, "trackbar Center")
trackbar_align#(c#, 13)
assert_eq(trackbar_align(c#), 13, "trackbar HorzCenter")
trackbar_align#(c#, 19)
assert_eq(trackbar_align(c#), 19, "trackbar FitRight")
